import 'package:flutter/material.dart';
import '../../services/api_service.dart';

class PaymentsScreen extends StatefulWidget{const PaymentsScreen({super.key});@override State<PaymentsScreen> createState()=>_PaymentsScreenState();}
class _PaymentsScreenState extends State<PaymentsScreen>{List items=[],students=[],subscriptions=[];bool loading=true;List<dynamic> list(dynamic x){if(x is List)return List<dynamic>.from(x);if(x is Map){final d=x['data'];if(d is List)return List<dynamic>.from(d);if(d is Map&&d['data'] is List)return List<dynamic>.from(d['data']);}return [];}int id(dynamic x)=>int.tryParse('${x['id']}')??0;String today()=>DateTime.now().toIso8601String().substring(0,10);void msg(Object e)=>ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString().replaceFirst('Exception: ',''))));
Future<void> pickDate(TextEditingController c)async{final initial=DateTime.tryParse(c.text.trim())??DateTime.now();final d=await showDatePicker(context:context,initialDate:initial,firstDate:DateTime(2000),lastDate:DateTime(2100),helpText:'اختر التاريخ');if(d!=null)c.text='${d.year.toString().padLeft(4,'0')}-${d.month.toString().padLeft(2,'0')}-${d.day.toString().padLeft(2,'0')}';}@override void initState(){super.initState();load();}
Future<void> load()async{if(mounted)setState(()=>loading=true);Object? primaryError;try{final r=await ApiService.get('payments');if(mounted)setState(()=>items=list(r));}catch(e){primaryError=e;}try{final r=await ApiService.get('students');if(mounted)setState(()=>students=list(r));}catch(e){if(primaryError==null)primaryError=e;}try{final r=await ApiService.get('subscriptions');if(mounted)setState(()=>subscriptions=list(r));}catch(e){if(primaryError==null)primaryError=e;}if(mounted){setState(()=>loading=false);if(primaryError!=null)msg(primaryError!);}}
Future<void> form({dynamic item})async{if(students.isEmpty){msg(Exception('أضف طالبًا أولًا.'));return;}int studentId=id(item?['student']??{'id':item?['student_id']});int? subscriptionId=int.tryParse('${item?['subscription_id']??''}');final amount=TextEditingController(text:'${item?['amount']??''}'),date=TextEditingController(text:'${item?['paid_on']??today()}'),method=TextEditingController(text:'${item?['method']??'نقدي'}');final k=GlobalKey<FormState>();final ok=await showDialog<bool>(context:context,builder:(d)=>StatefulBuilder(builder:(c,set)=>AlertDialog(title:Text(item==null?'إضافة دفعة':'تعديل الدفعة'),content:SingleChildScrollView(child:Form(key:k,child:Column(mainAxisSize:MainAxisSize.min,children:[DropdownButtonFormField<int>(value:students.any((s)=>id(s)==studentId)?studentId:null,decoration:const InputDecoration(labelText:'الطالب *'),items:students.map((s)=>DropdownMenuItem(value:id(s),child:Text('${s['name']}'))).toList(),validator:(v)=>v==null?'اختر الطالب':null,onChanged:(v){if(v!=null)set(()=>studentId=v);}),Builder(builder:(_){final av=subscriptions.where((s)=>'${s['student_id']??s['student']?['id']??''}'=='$studentId').toList();return DropdownButtonFormField<int?>(value:av.any((s)=>id(s)==subscriptionId)?subscriptionId:null,decoration:const InputDecoration(labelText:'الاشتراك'),items:[const DropdownMenuItem<int?>(value:null,child:Text('بدون اشتراك')),...av.map((s)=>DropdownMenuItem<int?>(value:id(s),child:Text('${s['subject']??''} • ${s['amount']??0}')))],onChanged:(v)=>set(()=>subscriptionId=v));}),TextFormField(controller:amount,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'المبلغ *'),validator:(v)=>double.tryParse(v??'')==null?'مبلغ غير صحيح':null),TextFormField(controller:date,readOnly:true,onTap:()=>pickDate(date),decoration:const InputDecoration(labelText:'التاريخ'),validator:(v)=>RegExp(r'^\d{4}-\d{2}-\d{2}$').hasMatch((v??'').trim())?'': 'التاريخ يجب أن يكون YYYY-MM-DD'),TextFormField(controller:method,decoration:const InputDecoration(labelText:'طريقة الدفع'))]))),actions:[TextButton(onPressed:()=>Navigator.pop(d,false),child:const Text('إلغاء')),FilledButton(onPressed:(){if(k.currentState!.validate())Navigator.pop(d,true);},child:const Text('حفظ'))])));if(ok==true){try{final b={'student_id':studentId,'subscription_id':subscriptionId,'amount':double.parse(amount.text),'paid_on':date.text.trim(),'method':method.text.trim().isEmpty?'نقدي':method.text.trim()};if(item==null)await ApiService.post('payments',b);else await ApiService.put('payments/${id(item)}',b);await load();}catch(e){msg(e);}}for(final c in[amount,date,method])c.dispose();}
Future<void> remove(dynamic p)async{final ok=await showDialog<bool>(context:context,builder:(d)=>AlertDialog(title:const Text('حذف الدفعة'),content:const Text('هل تريد الحذف؟'),actions:[TextButton(onPressed:()=>Navigator.pop(d,false),child:const Text('إلغاء')),FilledButton(onPressed:()=>Navigator.pop(d,true),child:const Text('حذف'))]));if(ok==true){try{await ApiService.delete('payments/${id(p)}');await load();}catch(e){msg(e);}}}
@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('المدفوعات'),actions:[IconButton(onPressed:load,icon:const Icon(Icons.refresh))]),floatingActionButton:FloatingActionButton.extended(onPressed:()=>form(),icon:const Icon(Icons.add),label:const Text('إضافة دفعة')),body:loading?const Center(child:CircularProgressIndicator()):RefreshIndicator(onRefresh:load,child:ListView.builder(padding:const EdgeInsets.fromLTRB(16,12,16,90),itemCount:items.length,itemBuilder:(_,i){final p=items[i],student=p['student'],subscription=p['subscription'];return Card(child:ListTile(title:Text('${student?['name']??'طالب'}'),subtitle:Text('الاشتراك: ${subscription?['subject']??'غير مرتبط'}\n${p['paid_on']??''} • ${p['method']??''}'),isThreeLine:true,trailing:Row(mainAxisSize:MainAxisSize.min,children:[Text('${p['amount']??0}'),IconButton(onPressed:()=>form(item:p),icon:const Icon(Icons.edit)),IconButton(onPressed:()=>remove(p),icon:const Icon(Icons.delete))])));})));
}
