import 'package:flutter/material.dart';
import '../../services/api_service.dart';

class SupervisorsScreen extends StatefulWidget { const SupervisorsScreen({super.key}); @override State<SupervisorsScreen> createState() => _SupervisorsScreenState(); }
class _SupervisorsScreenState extends State<SupervisorsScreen> {
  List supervisors=[]; bool loading=true;
  List<dynamic> list(dynamic x)=>x is List?List<dynamic>.from(x):(x is Map&&x['data'] is List?List<dynamic>.from(x['data']):[]);
  int id(dynamic x)=>int.tryParse('${x['id']}')??0;
  void msg(Object e)=>ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString().replaceFirst('Exception: ',''))));
  @override void initState(){super.initState();load();}
  Future<void> load()async{try{final r=await ApiService.get('supervisors');if(mounted)setState((){supervisors=list(r);loading=false;});}catch(e){if(mounted){setState(()=>loading=false);msg(e);}}}
  Future<void> add()async{final name=TextEditingController(),phone=TextEditingController(),email=TextEditingController();final form=GlobalKey<FormState>();final ok=await showDialog<bool>(context:context,builder:(dc)=>AlertDialog(title:const Text('إضافة مشرف'),content:Form(key:form,child:Column(mainAxisSize:MainAxisSize.min,children:[TextFormField(controller:name,decoration:const InputDecoration(labelText:'اسم المشرف *'),validator:(v)=>v==null||v.trim().isEmpty?'مطلوب':null),TextFormField(controller:phone,decoration:const InputDecoration(labelText:'الهاتف')),TextFormField(controller:email,decoration:const InputDecoration(labelText:'البريد'))])),actions:[TextButton(onPressed:()=>Navigator.pop(dc,false),child:const Text('إلغاء')),FilledButton(onPressed:(){if(form.currentState!.validate())Navigator.pop(dc,true);},child:const Text('حفظ'))]));if(ok==true){try{await ApiService.post('supervisors',{'name':name.text.trim(),'phone':phone.text.trim(),'email':email.text.trim(),'status':'active'});await load();}catch(e){msg(e);}}name.dispose();phone.dispose();email.dispose();}
  Future<void> details(int supervisorId)async{try{final r=await ApiService.get('supervisors/$supervisorId');final d=Map<String,dynamic>.from(r is Map&&r['data'] is Map?r['data']:r);if(!mounted)return;final privateLessons=list(d['private_lessons']),groupLessons=list(d['group_lessons']),history=list(d['lessons']);await showDialog<void>(context:context,builder:(dc)=>AlertDialog(title:Text('${d['supervisor']?['name']??'المشرف'}'),content:SizedBox(width:520,child:SingleChildScrollView(child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[Card(child:Padding(padding:const EdgeInsets.all(12),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('ملخص الإشراف',style:TextStyle(fontWeight:FontWeight.bold,fontSize:17)),Text('حصص خاصة: ${privateLessons.length}'),Text('حصص جروب: ${groupLessons.length}'),Text('إجمالي الحصص: ${d['lessons_count']??0}'),Text('المستحق: ${d['due']??0}'),Text('المدفوع: ${d['paid']??0}'),Text('المتبقي: ${d['remaining']??0}',style:const TextStyle(fontWeight:FontWeight.bold)),Text('المكافآت: ${d['bonus_total']??0}')]))),Card(child:Padding(padding:const EdgeInsets.all(12),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('سجل الحصص',style:TextStyle(fontWeight:FontWeight.bold,fontSize:17)),if(history.isEmpty)const Text('لا توجد حصص مرتبطة بهذا المشرف بعد.'),...history.map((x)=>ListTile(dense:true,leading:const Icon(Icons.event),title:Text('${x['subject']??''}'),subtitle:Text('${x['type']??''} • ${x['starts_at']??''}')))]))) ]))),actions:[TextButton(onPressed:()=>Navigator.pop(dc),child:const Text('إغلاق'))]));}catch(e){msg(e);}}
  @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('المشرفون'),actions:[IconButton(onPressed:load,icon:const Icon(Icons.refresh))]),floatingActionButton:FloatingActionButton.extended(onPressed:add,icon:const Icon(Icons.person_add),label:const Text('إضافة مشرف')),body:loading?const Center(child:CircularProgressIndicator()):RefreshIndicator(onRefresh:load,child:ListView(padding:const EdgeInsets.fromLTRB(16,12,16,90),children:[Card(child:Padding(padding:const EdgeInsets.all(14),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('طريقة العمل',style:TextStyle(fontWeight:FontWeight.bold,fontSize:17)),const SizedBox(height:4),const Text('أضف المشرف هنا، ثم اربطه بالحصة عند إنشاء حصة خاصة أو جروب. افتح اسم المشرف لرؤية الحصص والمستحق والمدفوع والمتبقي والمكافآت.')]))),if(supervisors.isEmpty)const Padding(padding:EdgeInsets.all(30),child:Center(child:Text('لا يوجد مشرفون بعد. اضغط «إضافة مشرف».'))),...supervisors.map((s)=>Card(child:ListTile(onTap:()=>details(id(s)),leading:const CircleAvatar(child:Icon(Icons.supervisor_account)),title:Text('${s['name']??''}',style:const TextStyle(fontWeight:FontWeight.bold)),subtitle:Text('${s['lessons_count']??s['lessons_count']??0} حصة'),trailing:const Icon(Icons.chevron_left))))])));
}
