import 'package:flutter/material.dart';
import '../../core/theme/app_theme.dart';
import '../../services/api_service.dart';

class ReportsScreen extends StatefulWidget { const ReportsScreen({super.key}); @override State<ReportsScreen> createState()=>_ReportsScreenState(); }
class _ReportsScreenState extends State<ReportsScreen>{Map<String,dynamic>?data;bool loading=true;String?error;late String month;@override void initState(){super.initState();final n=DateTime.now();month='${n.year}-${n.month.toString().padLeft(2,'0')}';loadReports();}
Future<void>loadReports()async{setState((){loading=true;error=null;});try{final r=await ApiService.get('reports/financial?month=$month');if(!mounted)return;setState((){data=r;loading=false;});}catch(e){if(!mounted)return;setState((){loading=false;error=e.toString().replaceFirst('Exception: ','');});}}
Future<void>changeMonth(int delta)async{final parts=month.split('-');var d=DateTime(int.parse(parts[0]),int.parse(parts[1])+delta,1);setState(()=>month='${d.year}-${d.month.toString().padLeft(2,'0')}');await loadReports();}
@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('التقارير المالية'),actions:[IconButton(onPressed:loading?null:loadReports,icon:const Icon(Icons.refresh))]),body:loading?const Center(child:CircularProgressIndicator()):error!=null?Center(child:Padding(padding:const EdgeInsets.all(24),child:Column(mainAxisSize:MainAxisSize.min,children:[const Icon(Icons.cloud_off,size:52),const SizedBox(height:12),Text(error!,textAlign:TextAlign.center),const SizedBox(height:16),FilledButton(onPressed:loadReports,child:const Text('إعادة المحاولة'))]))):RefreshIndicator(onRefresh:loadReports,child:ListView(padding:const EdgeInsets.all(16),children:[Card(child:ListTile(leading:IconButton(onPressed:()=>changeMonth(-1),icon:const Icon(Icons.chevron_right)),title:Center(child:Text(month,style:const TextStyle(fontSize:18,fontWeight:FontWeight.bold))),trailing:IconButton(onPressed:()=>changeMonth(1),icon:const Icon(Icons.chevron_left)))),_card('إجمالي الدخل',data?['income']??0),_card('إجمالي المصروفات',data?['expenses']??0),_card('مستحقات المدرسين',data?['teacher_dues']??0),_card('المدفوع للمدرسين',data?['teacher_paid']??0),_card('مستحقات المشرفين',data?['supervisor_dues']??0),_card('المدفوع للمشرفين',data?['supervisor_paid']??0),_card('صافي التشغيل',_number(data?['income'])-_number(data?['expenses'])-_number(data?['teacher_paid'])-_number(data?['supervisor_paid']))]));
double _number(dynamic v)=>v is num?v.toDouble():double.tryParse('$v')??0;Widget _card(String t,dynamic v)=>Card(margin:const EdgeInsets.only(bottom:12),child:ListTile(leading:const Icon(Icons.bar_chart,color:AppColors.red),title:Text(t),trailing:Text('$v',style:const TextStyle(fontSize:18,fontWeight:FontWeight.bold))));}
