import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../core/theme/app_theme.dart';
import '../../models/group_model.dart';
import '../../providers/groups_provider.dart';
class GroupsScreen extends StatelessWidget{const GroupsScreen({super.key});@override Widget build(BuildContext c)=>ChangeNotifierProvider(create:(x)=>GroupsProvider(x.read())..load(),child:const _GroupsView());}
class _GroupsView extends StatefulWidget{const _GroupsView();@override State<_GroupsView> createState()=>_GroupsViewState();}
class _GroupsViewState extends State<_GroupsView>{final search=TextEditingController();@override void dispose(){search.dispose();super.dispose();}
@override Widget build(BuildContext c){final s=c.watch<GroupsProvider>();return Scaffold(appBar:AppBar(title:const Text('المجموعات والفصول'),actions:[IconButton(onPressed:s.loading?null:()=>s.load(query:search.text),icon:const Icon(Icons.refresh_rounded))]),floatingActionButton:FloatingActionButton.extended(onPressed:()=>_form(c),backgroundColor:AppTheme.primary,foregroundColor:Colors.white,icon:const Icon(Icons.add),label:const Text('إضافة مجموعة')),body:Column(children:[Padding(padding:const EdgeInsets.fromLTRB(16,12,16,8),child:TextField(controller:search,textInputAction:TextInputAction.search,onSubmitted:(_)=>s.load(query:search.text),decoration:InputDecoration(hintText:'ابحث باسم المجموعة أو المدرس',prefixIcon:const Icon(Icons.search),suffixIcon:search.text.isEmpty?null:IconButton(onPressed:(){search.clear();s.load();setState((){});},icon:const Icon(Icons.clear))))),Expanded(child:RefreshIndicator(onRefresh:()=>s.load(query:search.text),child:s.loading&&s.groups.isEmpty?const Center(child:CircularProgressIndicator()):s.error!=null&&s.groups.isEmpty?_Error(s.error!,()=>s.load(query:search.text)):s.groups.isEmpty?const _Empty():ListView.separated(padding:const EdgeInsets.fromLTRB(16,8,16,100),itemCount:s.groups.length+(s.hasMore?1:0),separatorBuilder:(_,__)=>const SizedBox(height:8),itemBuilder:(_,i){if(i==s.groups.length)return const Padding(padding:EdgeInsets.all(16),child:Center(child:CircularProgressIndicator()));final g=s.groups[i];return _Card(group:g,onEdit:()=>_form(c,group:g),onDelete:()=>_delete(c,g));})))]) );}
Future<void> _form(BuildContext c,{GroupModel? group})async{final name=TextEditingController(text:group?.name??''),course=TextEditingController(text:group?.course??''),teacher=TextEditingController(text:group?.teacher??''),schedule=TextEditingController(text:group?.schedule??'');final key=GlobalKey<FormState>();await showModalBottomSheet(context:c,isScrollControlled:true,showDragHandle:true,builder:(sheet)=>Padding(padding:EdgeInsets.fromLTRB(20,8,20,MediaQuery.of(sheet).viewInsets.bottom+20),child:Form(key:key,child:SingleChildScrollView(child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[Text(group==null?'إضافة مجموعة':'تعديل المجموعة',style:const TextStyle(fontSize:20,fontWeight:FontWeight.w900)),const SizedBox(height:18),_field(name,'اسم المجموعة',Icons.groups_outlined,true),_field(course,'الكورس',Icons.menu_book_outlined,false),_field(teacher,'المدرس',Icons.person_outline,false),_field(schedule,'المواعيد',Icons.schedule_outlined,false),const SizedBox(height:18),FilledButton.icon(onPressed:()async{if(!key.currentState!.validate())return;final ok=await c.read<GroupsProvider>().save(id:group?.id,data:{'name':name.text.trim(),'course_name':course.text.trim(),'teacher_name':teacher.text.trim(),'schedule':schedule.text.trim()});if(ok&&sheet.mounted)Navigator.pop(sheet);},icon:const Icon(Icons.save_outlined),label:const Text('حفظ'))]))));for(final x in[name,course,teacher,schedule])x.dispose();}
Widget _field(TextEditingController x,String label,IconData icon,bool req)=>Padding(padding:const EdgeInsets.only(bottom:12),child:TextFormField(controller:x,decoration:InputDecoration(labelText:label,prefixIcon:Icon(icon)),validator:req?(v)=>(v==null||v.trim().isEmpty)?'هذا الحقل مطلوب':null:null));
Future<void> _delete(BuildContext c,GroupModel g)async{final yes=await showDialog<bool>(context:c,builder:(d)=>AlertDialog(title:const Text('حذف المجموعة'),content:Text('هل تريد حذف ${g.name}؟'),actions:[TextButton(onPressed:()=>Navigator.pop(d,false),child:const Text('إلغاء')),FilledButton(onPressed:()=>Navigator.pop(d,true),child:const Text('حذف'))]));if(yes==true&&c.mounted){final ok=await c.read<GroupsProvider>().remove(g.id);if(!ok&&c.mounted)ScaffoldMessenger.of(c).showSnackBar(SnackBar(content:Text(c.read<GroupsProvider>().error??'تعذر الحذف')));}}
}
class _Card extends StatelessWidget{final GroupModel group;final VoidCallback onEdit,onDelete;const _Card({required this.group,required this.onEdit,required this.onDelete});@override Widget build(BuildContext c)=>Card(child:ListTile(contentPadding:const EdgeInsets.symmetric(horizontal:14,vertical:8),leading:CircleAvatar(radius:26,backgroundColor:const Color(0xFFFFE8EA),child:const Icon(Icons.groups,color:AppTheme.primary)),title:Text(group.name.isEmpty?'بدون اسم':group.name,style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Padding(padding:const EdgeInsets.only(top:5),child:Text([group.course,group.teacher,group.schedule,group.studentsCount>0?'${group.studentsCount} طالب':''].where((x)=>x.isNotEmpty).join(' • '),maxLines:2,overflow:TextOverflow.ellipsis)),trailing:PopupMenuButton<String>(onSelected:(v){if(v=='edit')onEdit();else onDelete();},itemBuilder:(_)=>const[PopupMenuItem(value:'edit',child:Text('تعديل')),PopupMenuItem(value:'delete',child:Text('حذف'))])));}
class _Empty extends StatelessWidget{const _Empty();@override Widget build(BuildContext c)=>ListView(children:const[SizedBox(height:100),Icon(Icons.groups_outlined,size:60,color:Colors.grey),SizedBox(height:12),Center(child:Text('لا توجد مجموعات'))]);}
class _Error extends StatelessWidget{final String m;final VoidCallback r;const _Error(this.m,this.r);@override Widget build(BuildContext c)=>ListView(children:[const SizedBox(height:100),const Icon(Icons.cloud_off_outlined,size:52),const SizedBox(height:10),Center(child:Text(m)),TextButton(onPressed:r,child:const Text('إعادة المحاولة'))]);}
