import 'package:flutter/material.dart';
import '../../core/theme/app_theme.dart';
import '../../services/api_service.dart';

class TeachersScreen extends StatefulWidget { const TeachersScreen({super.key}); @override State<TeachersScreen> createState() => _TeachersScreenState(); }
class _TeachersScreenState extends State<TeachersScreen> {
  List teachers = [], students = [], subjects = [], supervisors = []; bool loading = true;
  static const fallbackSubjects = ['العربية','اللغة الإنجليزية','الرياضيات','العلوم','الدراسات الاجتماعية','Math','Science','English','Arabic','German','French','Spanish','Quran'];
  List<dynamic> list(dynamic x) => x is List ? List<dynamic>.from(x) : (x is Map && x['data'] is List ? List<dynamic>.from(x['data']) : []);
  int id(dynamic x) => int.tryParse('${x['id']}') ?? 0;
  void msg(Object e) => ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(e.toString().replaceFirst('Exception: ', ''))));
  @override void initState() { super.initState(); load(); }
  Future<void> load() async { try { final r = await Future.wait([ApiService.get('teachers'), ApiService.get('students'), ApiService.get('subjects'), ApiService.get('supervisors')]); if (!mounted) return; final ss=list(r[2]).map((e)=>'$e').where((e)=>e.trim().isNotEmpty).toList(); setState(() { teachers=list(r[0]); students=list(r[1]); subjects=ss.isEmpty?fallbackSubjects:ss; supervisors=list(r[3]); loading=false; }); } catch(e) { if(mounted){setState((){loading=false;subjects=fallbackSubjects;});msg(e);} } }

  Future<void> add() async {
    final n=TextEditingController(), p=TextEditingController(), e=TextEditingController(), s=TextEditingController(); final form=GlobalKey<FormState>();
    final ok=await showDialog<bool>(context:context,builder:(dc)=>AlertDialog(title:const Text('إضافة مدرس'),content:Form(key:form,child=Column(mainAxisSize:MainAxisSize.min,children:[TextFormField(controller:n,decoration:const InputDecoration(labelText:'اسم المدرس *'),validator:(v)=>v==null||v.trim().isEmpty?'مطلوب':null),TextFormField(controller:p,decoration:const InputDecoration(labelText:'الهاتف')),TextFormField(controller:e,decoration:const InputDecoration(labelText:'البريد')),TextFormField(controller:s,decoration:const InputDecoration(labelText:'التخصص'))])),actions:[TextButton(onPressed:()=>Navigator.pop(dc,false),child:const Text('إلغاء')),FilledButton(onPressed:(){if(form.currentState!.validate())Navigator.pop(dc,true);},child:const Text('حفظ'))]));
    if(ok==true){try{await ApiService.post('teachers',{'name':n.text.trim(),'phone':p.text.trim(),'email':e.text.trim(),'specialization':s.text.trim(),'status':'active'});await load();}catch(x){msg(x);}} for(final c in[n,p,e,s])c.dispose();
  }

  Future<void> details(int teacherId) async {
    try{
      final r=await ApiService.get('teachers/$teacherId'); final d=Map<String,dynamic>.from(r is Map&&r['data'] is Map?r['data']:r); if(!mounted)return;
      final studentsList=list(d['students']), assignments=list(d['assignments']), privateLessons=list(d['private_lessons']), groupLessons=list(d['group_lessons']);
      await showDialog(context:context,builder:(dc)=>AlertDialog(title:Text('${d['teacher']?['name']??'المدرس'}'),content:SizedBox(width:540,child:SingleChildScrollView(child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[
        _section('الطلاب المرتبطون', studentsList.isEmpty ? const [Text('لم يتم ربط طلاب بهذا المدرس بعد.')] : studentsList.map((x)=>ListTile(dense:true,leading:const Icon(Icons.person),title:Text('${x['name']??''}'))).toList()),
        _section('أسعار الحصص والربط', assignments.isEmpty ? const [Text('لا توجد علاقة طالب/مادة/سعر بعد. اضغط «ربط طالب ومادة» للبدء.')] : assignments.map((x){final rate=double.tryParse('${x['teacher_rate']??0}')??0;final pct=double.tryParse('${x['academy_percentage']??0}')??0;final total=rate*(1+pct/100);return ListTile(dense:true,leading:const Icon(Icons.payments),title:Text('${x['student']?['name']??''} — ${x['subject']??''}'),subtitle:Text('سعر المدرس: ${rate.toStringAsFixed(2)} • نسبة الأكاديمية: ${pct.toStringAsFixed(2)}% • الإجمالي: ${total.toStringAsFixed(2)}'));}).toList()),
        _section('الحصص', [Text('خاصة: ${privateLessons.length}'),Text('جروب: ${groupLessons.length}'),const SizedBox(height:6),Text('المستحق: ${d['due']??0}'),Text('المدفوع: ${d['paid']??0}'),Text('المتبقي: ${d['remaining']??0}',style:const TextStyle(fontWeight:FontWeight.bold))]),
        const SizedBox(height:8),FilledButton.icon(onPressed:(){Navigator.pop(dc);assignmentDialog(teacherId);},icon:const Icon(Icons.link),label:const Text('ربط طالب + مادة + سعر الحصة'))
      ]))),actions:[TextButton(onPressed:()=>Navigator.pop(dc),child:const Text('إغلاق'))]));
    }catch(e){msg(e);}
  }
  Widget _section(String title,List<Widget> children)=>Padding(padding:const EdgeInsets.only(bottom:10),child:Card(child:Padding(padding:const EdgeInsets.all(10),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:const TextStyle(fontWeight:FontWeight.bold,fontSize:16)),const SizedBox(height:5),...children]))));

  Future<void> assignmentDialog(int teacherId) async {
    if(students.isEmpty){msg(Exception('أضف طالبًا أولًا ثم اربطه بالمدرس'));return;}
    int studentId=id(students.first); String subject=subjects.first; int? supervisorId; final rate=TextEditingController(), pct=TextEditingController(); final form=GlobalKey<FormState>();
    final ok=await showDialog<bool>(context:context,builder:(dc)=>StatefulBuilder(builder:(context,setD){final total=(double.tryParse(rate.text)??0)*(1+(double.tryParse(pct.text)??0)/100);return AlertDialog(title:const Text('ربط المدرس بالطالب'),content:SingleChildScrollView(child:Form(key:form,child:Column(mainAxisSize:MainAxisSize.min,children:[const Text('هنا تحدد من يدرّس الطالب، المادة، سعر الحصة، ونسبة الأكاديمية.'),DropdownButtonFormField<int>(value:studentId,decoration:const InputDecoration(labelText:'الطالب *'),items:students.map((x)=>DropdownMenuItem<int>(value:id(x),child:Text('${x['name']}'))).toList(),onChanged:(v){if(v!=null)setD(()=>studentId=v);}),DropdownButtonFormField<String>(value:subject,decoration:const InputDecoration(labelText:'المادة *'),items:subjects.map((x)=>DropdownMenuItem<String>(value:'$x',child:Text('$x'))).toList(),onChanged:(v){if(v!=null)setD(()=>subject=v);}),TextFormField(controller:rate,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'سعر الحصة للمدرس *'),validator:(v)=>double.tryParse(v??'')==null?'أدخل السعر':null,onChanged:(_)=>setD((){})),TextFormField(controller:pct,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'نسبة الأكاديمية %'),onChanged:(_)=>setD((){})),if(supervisors.isNotEmpty)DropdownButtonFormField<int?>(value:supervisorId,decoration:const InputDecoration(labelText:'المشرف (اختياري)'),items:[const DropdownMenuItem<int?>(value:null,child:Text('بدون مشرف')),...supervisors.map((x)=>DropdownMenuItem<int?>(value:id(x),child:Text('${x['name']}')))],onChanged:(v)=>setD(()=>supervisorId=v)),const SizedBox(height:8),Text('الإجمالي النهائي: ${total.toStringAsFixed(2)}',style:const TextStyle(fontWeight:FontWeight.bold))]))),actions:[TextButton(onPressed:()=>Navigator.pop(dc,false),child:const Text('إلغاء')),FilledButton(onPressed:(){if(form.currentState!.validate())Navigator.pop(dc,true);},child:const Text('حفظ العلاقة'))]);}));
    if(ok==true){try{await ApiService.post('teacher-assignments',{'teacher_id':teacherId,'student_id':studentId,'subject':subject,'teacher_rate':double.tryParse(rate.text)??0,'academy_percentage':double.tryParse(pct.text)??0,'supervisor_id':supervisorId});await load();}catch(e){msg(e);}} rate.dispose();pct.dispose();
  }
  @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('المدرسون'),actions:[IconButton(onPressed:load,icon:const Icon(Icons.refresh))]),floatingActionButton:FloatingActionButton.extended(onPressed:add,backgroundColor:AppColors.red,icon:const Icon(Icons.person_add),label:const Text('إضافة مدرس')),body:loading?const Center(child:CircularProgressIndicator()):RefreshIndicator(onRefresh:load,child:ListView(padding:const EdgeInsets.fromLTRB(16,12,16,90),children:[Card(child:Padding(padding:const EdgeInsets.all(14),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('طريقة العمل',style:TextStyle(fontWeight:FontWeight.bold,fontSize:17)),const SizedBox(height:4),const Text('1) أضف المدرس  2) اضغط على اسمه  3) اربطه بالطالب والمادة وحدد سعر الحصة  4) أنشئ الحصة من شاشة الدروس والحصص.')]))),if(teachers.isEmpty)const Padding(padding:EdgeInsets.all(30),child:Center(child:Text('لا يوجد مدرسون بعد. اضغط «إضافة مدرس».'))),...teachers.map((t)=>Card(child:ListTile(onTap:()=>details(id(t)),leading:const CircleAvatar(child:Icon(Icons.school)),title:Text('${t['name']??''}',style:const TextStyle(fontWeight:FontWeight.bold)),subtitle:Text('${t['phone']??t['email']??''}'),trailing:const Icon(Icons.chevron_left))))])));
}
