import 'package:flutter/material.dart';
import '../../core/theme/app_theme.dart';
import '../../services/api_service.dart';

class TeachersScreen extends StatefulWidget { const TeachersScreen({super.key}); @override State<TeachersScreen> createState()=>_TeachersScreenState(); }
class _TeachersScreenState extends State<TeachersScreen>{List teachers=[];bool loading=true;@override void initState(){super.initState();load();}Future<void> load()async{try{final r=await ApiService.get('teachers');if(mounted)setState((){teachers=r['data']??[];loading=false;});}catch(e){if(mounted)setState(()=>loading=false);}}
Future<void> add()async{final key=GlobalKey<FormState>();final n=TextEditingController(),p=TextEditingController(),e=TextEditingController(),sp=TextEditingController(),rate=TextEditingController();final ok=await showDialog<bool>(context:context,builder:(c)=>AlertDialog(title:const Text('إضافة مدرس'),content:SingleChildScrollView(child:Form(key:key,child:Column(mainAxisSize:MainAxisSize.min,children:[TextFormField(controller:n,decoration:const InputDecoration(labelText:'اسم المدرس'),validator:(v)=>v!.trim().isEmpty?'اكتب الاسم':null),TextFormField(controller:p,decoration:const InputDecoration(labelText:'الهاتف')),TextFormField(controller:e,decoration:const InputDecoration(labelText:'البريد الإلكتروني')),TextFormField(controller:sp,decoration:const InputDecoration(labelText:'التخصص')),TextFormField(controller:rate,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'الأجر'))]))),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('إلغاء')),FilledButton(onPressed:(){if(key.currentState!.validate())Navigator.pop(c,true);},child:const Text('حفظ'))]));if(ok!=true)return;try{await ApiService.post('teachers',{'name':n.text.trim(),'phone':p.text.trim(),'email':e.text.trim().isEmpty?null:e.text.trim(),'specialization':sp.text.trim(),'hourly_rate':double.tryParse(rate.text.trim()),'status':'active'});await load();_msg('تمت إضافة المدرس');}catch(x){_msg(x.toString().replaceFirst('Exception: ',''));}}
Future<void> details(dynamic id)async{try{final r=await ApiService.get('teachers/$id');final d=r['data']??r;final t=d['teacher']??{};final ss=d['students']??[];final groups=d['groups']??[];showDialog(context:context,builder:(c)=>AlertDialog(title:Text('${t['name']??'المدرس'}'),content:SingleChildScrollView(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('الطلاب: ${ss.length}'),Text('المجموعات: ${groups.length}'),Text('إجمالي المستحق: ${d['due']??0}'),Text('المدفوع: ${d['paid']??0}'),Text('المتبقي: ${d['remaining']??0}'),const Divider(),...ss.map<Widget>((x)=>ListTile(dense:true,title:Text('${x['name']??''}'),leading:const Icon(Icons.person))) ])),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('إغلاق'))]));}catch(e){_msg(e.toString().replaceFirst('Exception: ',''));}}
void _msg(String x){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(x)));}
@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('المدرسون')),floatingActionButton:FloatingActionButton(onPressed:add,child:const Icon(Icons.add)),body:loading?const Center(child:CircularProgressIndicator()):RefreshIndicator(onRefresh:load,child:ListView.builder(padding:const EdgeInsets.all(16),itemCount:teachers.length,itemBuilder:(_,i){final t=teachers[i];return Card(child:ListTile(onTap:()=>details(t['id']),leading:CircleAvatar(backgroundColor:AppColors.black,child:Text('${i+1}',style:const TextStyle(color:Colors.white))),title:Text('${t['name']??''}',style:const TextStyle(fontWeight:FontWeight.bold)),subtitle:Text('${t['phone']??t['email']??''}'),trailing:const Icon(Icons.chevron_left)));}));}
}
