import 'package:flutter/material.dart';
import '../../core/theme/app_theme.dart';
import '../../services/api_service.dart';

class TeachersScreen extends StatefulWidget { const TeachersScreen({super.key}); @override State<TeachersScreen> createState()=>_TeachersScreenState(); }
class _TeachersScreenState extends State<TeachersScreen>{
 List teachers=[],students=[],subjects=[],supervisors=[];bool loading=true;static const fallback=['العربية','اللغة الإنجليزية','الرياضيات','العلوم','الدراسات الاجتماعية','Math','Science','English','Arabic','German','French','Spanish','Quran'];
 List<dynamic> list(dynamic x)=>x is List?List<dynamic>.from(x):(x is Map&&x['data'] is List?List<dynamic>.from(x['data']):[]);int id(dynamic x)=>int.tryParse('${x['id']}')??0;void msg(Object e)=>ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString().replaceFirst('Exception: ',''))));
 @override void initState(){super.initState();load();}
 Future<void> load()async{try{final r=await Future.wait([ApiService.get('teachers'),ApiService.get('students'),ApiService.get('subjects'),ApiService.get('supervisors')]);if(!mounted)return;final ss=list(r[2]).map((e)=>'$e').where((e)=>e.trim().isNotEmpty).toList();setState((){teachers=list(r[0]);students=list(r[1]);subjects=ss.isEmpty?fallback:ss;supervisors=list(r[3]);loading=false;});}catch(e){if(mounted){setState((){loading=false;subjects=fallback;});msg(e);}}}
 Future<void> edit(dynamic t)async{final n=TextEditingController(text:'${t['name']??''}'),p=TextEditingController(text:'${t['phone']??''}'),e=TextEditingController(text:'${t['email']??''}'),s=TextEditingController(text:'${t['specialization']??''}');final k=GlobalKey<FormState>();final ok=await showDialog<bool>(context:context,builder:(d)=>AlertDialog(title:const Text('تعديل المدرس'),content:Form(key:k,child:Column(mainAxisSize:MainAxisSize.min,children:[TextFormField(controller:n,decoration:const InputDecoration(labelText:'الاسم *'),validator:(v)=>v==null||v.trim().isEmpty?'مطلوب':null),TextFormField(controller:p,decoration:const InputDecoration(labelText:'الهاتف')),TextFormField(controller:e,decoration:const InputDecoration(labelText:'البريد')),TextFormField(controller:s,decoration:const InputDecoration(labelText:'التخصص'))])),actions:[TextButton(onPressed:()=>Navigator.pop(d,false),child:const Text('إلغاء')),FilledButton(onPressed:(){if(k.currentState!.validate())Navigator.pop(d,true);},child:const Text('حفظ'))]));if(ok==true){try{await ApiService.put('teachers/${id(t)}',{'name':n.text.trim(),'phone':p.text.trim(),'email':e.text.trim(),'specialization':s.text.trim()});await load();}catch(e){msg(e);}}for(final c in[n,p,e,s])c.dispose();}
 Future<void> remove(dynamic t)async{final ok=await showDialog<bool>(context:context,builder:(d)=>AlertDialog(title:const Text('حذف المدرس'),content:Text('حذف ${t['name']??''}؟'),actions:[TextButton(onPressed:()=>Navigator.pop(d,false),child:const Text('إلغاء')),FilledButton(onPressed:()=>Navigator.pop(d,true),child:const Text('حذف'))]));if(ok==true){try{await ApiService.delete('teachers/${id(t)}');await load();}catch(e){msg(e);}}}
 Future<void> add()async{final n=TextEditingController(),p=TextEditingController(),e=TextEditingController(),s=TextEditingController();final k=GlobalKey<FormState>();final ok=await showDialog<bool>(context:context,builder:(d)=>AlertDialog(title:const Text('إضافة مدرس'),content:Form(key:k,child:Column(mainAxisSize:MainAxisSize.min,children:[TextFormField(controller:n,decoration:const InputDecoration(labelText:'الاسم *'),validator:(v)=>v==null||v.trim().isEmpty?'مطلوب':null),TextFormField(controller:p,decoration:const InputDecoration(labelText:'الهاتف')),TextFormField(controller:e,decoration:const InputDecoration(labelText:'البريد')),TextFormField(controller:s,decoration:const InputDecoration(labelText:'التخصص'))])),actions:[TextButton(onPressed:()=>Navigator.pop(d,false),child:const Text('إلغاء')),FilledButton(onPressed:(){if(k.currentState!.validate())Navigator.pop(d,true);},child:const Text('حفظ'))]));if(ok==true){try{await ApiService.post('teachers',{'name':n.text.trim(),'phone':p.text.trim(),'email':e.text.trim(),'specialization':s.text.trim(),'status':'active'});await load();}catch(e){msg(e);}}for(final c in[n,p,e,s])c.dispose();}
 Future<void> details(int teacherId)async{try{final r=await ApiService.get('teachers/$teacherId');final d=Map<String,dynamic>.from(r is Map&&r['data'] is Map?r['data']:r);if(!mounted)return;final sl=list(d['students']),a=list(d['assignments']),pl=list(d['private_lessons']),gl=list(d['group_lessons']);await showDialog(context:context,builder:(dc)=>AlertDialog(title:Text('${d['teacher']?['name']??'المدرس'}'),content:SizedBox(width:540,child:SingleChildScrollView(child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[Text('الطلاب المرتبطون: ${sl.length}'),Text('العلاقات والأسعار: ${a.length}'),Text('الحصص الخاصة: ${pl.length}'),Text('حصص الجروب: ${gl.length}'),Text('المستحق: ${d['due']??0}'),Text('المدفوع: ${d['paid']??0}'),Text('المتبقي: ${d['remaining']??0}'),const SizedBox(height:10),FilledButton.icon(onPressed:(){Navigator.pop(dc);},icon:const Icon(Icons.close),label:const Text('إغلاق'))]))),actions:[]));}catch(e){msg(e);}}
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('المدرسون'),actions:[IconButton(onPressed:load,icon:const Icon(Icons.refresh))]),floatingActionButton:FloatingActionButton.extended(onPressed:add,backgroundColor:AppColors.red,icon:const Icon(Icons.person_add),label:const Text('إضافة مدرس')),body:loading?const Center(child:CircularProgressIndicator()):RefreshIndicator(onRefresh:load,child:ListView(padding:const EdgeInsets.fromLTRB(16,12,16,90),children:[Card(child:Padding(padding:const EdgeInsets.all(14),child:const Text('أضف المدرس، ثم عدّل أو احذفه من القائمة. الربط بالطالب والمادة وسعر الحصة يتم من تفاصيل المدرس.'))),if(teachers.isEmpty)const Padding(padding:EdgeInsets.all(30),child:Center(child:Text('لا يوجد مدرسون.'))),...teachers.map((t)=>Card(child:ListTile(onTap:()=>details(id(t)),leading:const CircleAvatar(child:Icon(Icons.school)),title:Text('${t['name']??''}',style:const TextStyle(fontWeight:FontWeight.bold)),subtitle:Text('${t['phone']??t['email']??''}'),trailing:Row(mainAxisSize:MainAxisSize.min,children:[IconButton(onPressed:()=>edit(t),icon:const Icon(Icons.edit)),IconButton(onPressed:()=>remove(t),icon:const Icon(Icons.delete))]))))])));
}
