import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';
import '../../services/api_service.dart';
class ParentsScreen extends StatefulWidget{const ParentsScreen({super.key});@override State<ParentsScreen> createState()=>_ParentsScreenState();}
class _ParentGroup{final String name,phone;final List<dynamic> children;_ParentGroup(this.name,this.phone,this.children);}
class _ParentsScreenState extends State<ParentsScreen>{List students=[];bool loading=true;String? error;List<dynamic> list(dynamic x){if(x is List)return List<dynamic>.from(x);if(x is Map&&x['data'] is List)return List<dynamic>.from(x['data']);if(x is Map&&x['data'] is Map&&x['data']['data'] is List)return List<dynamic>.from(x['data']['data']);return[];}int id(dynamic x)=>int.tryParse('${x['id']}')??0;String names(dynamic v,String key)=>list(v).map((x)=>x is Map?'${x[key]??x['name']??''}':'$x').where((x)=>x.isNotEmpty).join('، ');void msg(Object e)=>ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('$e'.replaceFirst('Exception: ',''))));@override void initState(){super.initState();load();}Future<void> load()async{if(mounted)setState(()=>loading=true);try{students=list(await ApiService.get('students'));if(mounted)setState(()=>error=null);}catch(e){if(mounted)setState(()=>error=e.toString().replaceFirst('Exception: ',''));}if(mounted)setState(()=>loading=false);}List<_ParentGroup> groups(){final map=<String,_ParentGroup>{};for(final raw in students){if(raw is! Map)continue;final n='${raw['parent_name']??''}'.trim(),p='${raw['parent_phone']??''}'.trim();if(n.isEmpty&&p.isEmpty)continue;final k='${p.toLowerCase()}|${n.toLowerCase()}';map.putIfAbsent(k,()=>_ParentGroup(n.isEmpty?'ولي أمر بدون اسم':n,p,[])).children.add(raw);}final r=map.values.toList();r.sort((a,b)=>a.name.compareTo(b.name));return r;}
Future<void> openUrl(String raw)async{final u=Uri.tryParse(raw);if(u!=null&&await canLaunchUrl(u)){await launchUrl(u,mode:LaunchMode.externalApplication);}else{msg('الرابط غير صالح');}}
Future<void> details(_ParentGroup parent)async{final loaded=[];for(final child in parent.children){try{final r=await ApiService.get('academic/students/${id(child)}');loaded.add(r is Map&&r['data'] is Map?r['data']:r);}catch(_){loaded.add(child);}}if(!mounted)return;await showDialog(context:context,builder:(d)=>AlertDialog(title:Text(parent.name),content:SizedBox(width:650,child:SingleChildScrollView(child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[if(parent.phone.isNotEmpty)Text('هاتف ولي الأمر: ${parent.phone}'),Text('عدد الأبناء: ${loaded.length}',style:const TextStyle(fontWeight:FontWeight.bold)),...loaded.map((c){final m=c is Map?c:<String,dynamic>{};final st=m['student'] is Map?m['student']:m;final resources=list(m['resources']),evals=list(m['evaluations']);return Card(child:Padding(padding:const EdgeInsets.all(10),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[Text('${st['name']??'طالب'}',style:const TextStyle(fontWeight:FontWeight.bold)),Text('الصف: ${st['grade']??'-'}'),Text('المواد: ${names(st['subjects'],'subject')}'),Text('المدرسون: ${names(st['teachers'],'name')}'),Text('المجموعات: ${names(st['groups'],'name')}'),Text('الحصص: ${list(st['lessons']).length} • الاشتراكات: ${list(st['subscriptions']).length} • المدفوعات: ${list(st['payments']).length}'),if(evals.isNotEmpty)...[const Divider(),const Text('التقييمات',style:TextStyle(fontWeight:FontWeight.bold)),...evals.map((e)=>Text('• ${e['title']??'تقييم'} — ${e['score']??'-'}%'))],if(resources.isNotEmpty)...[const Divider(),const Text('الواجبات والامتحانات والروابط والمرفقات',style:TextStyle(fontWeight:FontWeight.bold)),...resources.map((x)=>ListTile(dense:true,title:Text('${x['title']??''}'),subtitle:Text('${x['type']??''} • ${x['description']??''}'),trailing:x['url']==null?null:IconButton(onPressed:()=>openUrl('${x['url']}'),icon:const Icon(Icons.open_in_new))))]]));})])),),actions:[TextButton(onPressed:()=>Navigator.pop(d),child:const Text('إغلاق'))]));}
@override Widget build(BuildContext context){final parents=groups();return Scaffold(appBar:AppBar(title:const Text('أولياء الأمور'),actions:[IconButton(onPressed:load,icon:const Icon(Icons.refresh))]),body:loading?const Center(child:CircularProgressIndicator()):error!=null?Center(child:Column(mainAxisSize:MainAxisSize.min,children:[Text(error!),const SizedBox(height:12),FilledButton(onPressed:load,child:const Text('إعادة المحاولة'))])):RefreshIndicator(onRefresh:load,child:parents.isEmpty?ListView(children:const[SizedBox(height:180),Center(child:Text('لا يوجد أولياء أمور مسجلون.'))]):ListView.builder(padding:const EdgeInsets.all(12),itemCount:parents.length,itemBuilder:(context,i){final p=parents[i];return Card(child:ListTile(onTap:()=>details(p),leading:const CircleAvatar(child:Icon(Icons.family_restroom)),title:Text(p.name),subtitle:Text('${p.phone.isEmpty?'بدون هاتف':p.phone} • ${p.children.length} ${p.children.length==1?'ابن':'أبناء'}'),trailing:const Icon(Icons.chevron_left)));}));}
}
