<?php
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ApiController;
use App\Http\Controllers\FinanceController;
use App\Http\Controllers\LessonController;
use App\Http\Controllers\TeacherAssignmentController;
use App\Http\Controllers\ManagementCrudController;
use App\Http\Controllers\UserController;
Route::get('/health',fn()=>['status'=>'ok','service'=>'osa-api','version'=>'1.4']);Route::post('/login',[ApiController::class,'login']);
Route::middleware('auth:sanctum')->group(function(){
 Route::get('/user',fn()=>request()->user());Route::post('/logout',[ApiController::class,'logout']);Route::get('/dashboard',[ApiController::class,'dashboard']);Route::get('/subjects',[ApiController::class,'subjects']);
 Route::middleware('admin')->group(function(){Route::get('/users',[UserController::class,'index']);Route::put('/users/{user}/permissions',[UserController::class,'updatePermissions']);});
 Route::middleware('permission:view_students')->group(function(){Route::get('/students',[ApiController::class,'index']);Route::get('/students/{student}',[ApiController::class,'show']);});
 Route::middleware('permission:manage_students')->group(function(){Route::post('/students',[ApiController::class,'store']);Route::put('/students/{student}',[ApiController::class,'update']);Route::patch('/students/{student}',[ApiController::class,'update']);Route::delete('/students/{student}',[ApiController::class,'destroy']);});
 Route::middleware('permission:view_teachers')->group(function(){Route::get('/teachers',[ApiController::class,'teachers']);Route::get('/teachers/{teacher}',[ApiController::class,'teacherDetails']);});
 Route::middleware('permission:manage_teachers')->group(function(){Route::post('/teachers',[ApiController::class,'storeTeacher']);Route::put('/teachers/{teacher}',[ManagementCrudController::class,'updateTeacher']);Route::patch('/teachers/{teacher}',[ManagementCrudController::class,'updateTeacher']);Route::delete('/teachers/{teacher}',[ManagementCrudController::class,'destroyTeacher']);Route::post('/teacher-assignments',[TeacherAssignmentController::class,'store']);Route::put('/teacher-assignments/{assignment}',[TeacherAssignmentController::class,'update']);Route::patch('/teacher-assignments/{assignment}',[TeacherAssignmentController::class,'update']);Route::delete('/teacher-assignments/{assignment}',[TeacherAssignmentController::class,'destroy']);});
 Route::middleware('permission:view_supervisors')->group(function(){Route::get('/supervisors',[ApiController::class,'supervisors']);Route::get('/supervisors/{supervisor}',[ApiController::class,'supervisorDetails']);});
 Route::middleware('permission:manage_supervisors')->group(function(){Route::post('/supervisors',[ApiController::class,'storeSupervisor']);Route::put('/supervisors/{supervisor}',[ApiController::class,'updateSupervisor']);Route::patch('/supervisors/{supervisor}',[ApiController::class,'updateSupervisor']);Route::delete('/supervisors/{supervisor}',[ApiController::class,'destroySupervisor']);});
 Route::middleware('permission:view_groups')->group(function(){Route::get('/groups',[ApiController::class,'groups']);});Route::middleware('permission:manage_groups')->group(function(){Route::post('/groups',[ApiController::class,'storeGroup']);Route::put('/groups/{group}',[ApiController::class,'updateGroup']);Route::patch('/groups/{group}',[ApiController::class,'updateGroup']);Route::delete('/groups/{group}',[ApiController::class,'destroyGroup']);Route::post('/groups/{group}/students',[ApiController::class,'addStudentToGroup']);Route::delete('/groups/{group}/students/{student}',[ApiController::class,'removeStudentFromGroup']);});
 Route::middleware('permission:view_schedules')->group(function(){Route::get('/schedules',[ApiController::class,'schedules']);});Route::middleware('permission:manage_schedules')->group(function(){Route::post('/schedules',[ApiController::class,'storeSchedule']);});Route::middleware('permission:view_attendance')->group(function(){Route::get('/attendance',[ApiController::class,'attendance']);});Route::middleware('permission:manage_attendance')->group(function(){Route::post('/attendance',[ApiController::class,'storeAttendance']);});
 Route::middleware('permission:view_subscriptions')->group(function(){Route::get('/subscriptions',[ApiController::class,'subscriptions']);});Route::middleware('permission:manage_subscriptions')->group(function(){Route::post('/subscriptions',[ApiController::class,'storeSubscription']);Route::put('/subscriptions/{subscription}',[ManagementCrudController::class,'updateSubscription']);Route::patch('/subscriptions/{subscription}',[ManagementCrudController::class,'updateSubscription']);Route::delete('/subscriptions/{subscription}',[ManagementCrudController::class,'destroySubscription']);});
 Route::middleware('permission:view_finance')->group(function(){Route::get('/payments',[ApiController::class,'payments']);Route::get('/expenses',[ApiController::class,'expenses']);Route::get('/teacher-dues',[ApiController::class,'teacherDues']);Route::get('/reports/financial',[ApiController::class,'financialReport']);Route::get('/finance/teacher-dues',[FinanceController::class,'teacherDues']);Route::get('/finance/supervisor-dues',[FinanceController::class,'supervisorDues']);Route::get('/finance/bonuses',[FinanceController::class,'bonuses']);Route::get('/finance/withdrawal-settings',[FinanceController::class,'withdrawalSettings']);Route::get('/finance/withdrawals',[FinanceController::class,'withdrawals']);Route::get('/finance/summary',[FinanceController::class,'summary']);});
 Route::middleware('permission:manage_finance')->group(function(){Route::post('/payments',[ApiController::class,'storePayment']);Route::put('/payments/{payment}',[ManagementCrudController::class,'updatePayment']);Route::patch('/payments/{payment}',[ManagementCrudController::class,'updatePayment']);Route::delete('/payments/{payment}',[ManagementCrudController::class,'destroyPayment']);Route::post('/expenses',[ApiController::class,'storeExpense']);Route::post('/finance/bonuses',[FinanceController::class,'storeBonus']);Route::post('/finance/withdrawal-settings',[FinanceController::class,'updateWithdrawalSetting']);Route::post('/finance/withdrawals',[FinanceController::class,'storeWithdrawal']);Route::put('/finance/withdrawals/{withdrawal}',[FinanceController::class,'updateWithdrawal']);Route::post('/finance/dues/{type}/{due}/pay',[FinanceController::class,'payDue']);});
 Route::middleware('permission:view_lessons')->group(function(){Route::get('/lessons',[LessonController::class,'index']);Route::get('/lessons/{lesson}',[LessonController::class,'show']);});Route::middleware('permission:manage_lessons')->group(function(){Route::post('/lessons',[LessonController::class,'store']);Route::put('/lessons/{lesson}',[LessonController::class,'update']);Route::patch('/lessons/{lesson}',[LessonController::class,'update']);Route::delete('/lessons/{lesson}',[LessonController::class,'destroy']);Route::post('/lessons/{lesson}/complete',[LessonController::class,'complete']);Route::post('/lessons/{lesson}/cancel',[LessonController::class,'cancel']);});
});
