import 'package:flutter/material.dart';
import '../../services/api_service.dart';
class GroupsScreen extends StatefulWidget{const GroupsScreen({super.key});@override State<GroupsScreen> createState()=>_GroupsScreenState();}
class _GroupsScreenState extends State<GroupsScreen>{
 List groups=[],students=[],teachers=[],subjects=[],supervisors=[];bool loading=true;
 static const fallbackSubjects=['العربية','اللغة الإنجليزية','الرياضيات','العلوم','الدراسات الاجتماعية','Math','Science','English','Arabic','German','French','Spanish','Quran'];
 List<dynamic> list(dynamic x)=>x is List?List<dynamic>.from(x):(x is Map&&x['data'] is List?List<dynamic>.from(x['data']):[]);
 int id(dynamic x)=>int.tryParse('${x['id']}')??0;
 void msg(Object e)=>ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString().replaceFirst('Exception: ',''))));
 @override void initState(){super.initState();load();}
 Future<void> load()async{try{final r=await Future.wait([ApiService.get('groups'),ApiService.get('students'),ApiService.get('teachers'),ApiService.get('subjects'),ApiService.get('supervisors')]);if(mounted){final ss=list(r[3]).map((e)=>'$e').where((e)=>e.trim().isNotEmpty).toList();setState((){groups=list(r[0]);students=list(r[1]);teachers=list(r[2]);subjects=ss.isEmpty?fallbackSubjects:ss;supervisors=list(r[4]);loading=false;});}}catch(e){if(mounted){setState((){loading=false;subjects=fallbackSubjects;});msg(e);}}}
 Future<void> add()async{
  if(teachers.isEmpty){msg(Exception('أضف مدرسًا أولًا من شاشة المدرسين.'));return;}if(students.isEmpty){msg(Exception('أضف طلابًا أولًا من شاشة الطلاب.'));return;}
  int teacherId=id(teachers.first);String subject=subjects.first;int? supervisorId;final name=TextEditingController(),rate=TextEditingController(),grade=TextEditingController();final selected=<int>{};final form=GlobalKey<FormState>();
  final ok=await showDialog<bool>(context:context,builder:(dc)=>StatefulBuilder(builder:(context,setD)=>AlertDialog(title:const Text('إنشاء مجموعة'),content:SizedBox(width:520,child:SingleChildScrollView(child:Form(key:form,child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[const Text('المجموعة هي التي ستختارها لاحقًا عند إنشاء «حصة جروب». اختر المدرس والمادة والطلاب وسعر الحصة.'),TextFormField(controller:name,decoration:const InputDecoration(labelText:'اسم المجموعة *'),validator:(v)=>v==null||v.trim().isEmpty?'مطلوب':null),TextFormField(controller:grade,decoration:const InputDecoration(labelText:'الصف')),DropdownButtonFormField<int>(value:teacherId,decoration:const InputDecoration(labelText:'المدرس *'),items:teachers.map((x)=>DropdownMenuItem<int>(value:id(x),child:Text('${x['name']}'))).toList(),onChanged:(v){if(v!=null)setD(()=>teacherId=v);}),DropdownButtonFormField<String>(value:subject,decoration:const InputDecoration(labelText:'المادة *'),items:subjects.map((x)=>DropdownMenuItem<String>(value:'$x',child:Text('$x'))).toList(),onChanged:(v){if(v!=null)setD(()=>subject=v);}),TextFormField(controller:rate,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'سعر الحصة للمدرس *'),validator:(v)=>double.tryParse(v??'')==null?'أدخل السعر':null),if(supervisors.isNotEmpty)DropdownButtonFormField<int?>(value:supervisorId,decoration:const InputDecoration(labelText:'المشرف (اختياري)'),items:[const DropdownMenuItem<int?>(value:null,child:Text('بدون مشرف')),...supervisors.map((x)=>DropdownMenuItem<int?>(value:id(x),child:Text('${x['name']}')))],onChanged:(v)=>setD(()=>supervisorId=v)),const SizedBox(height:8),const Text('طلاب المجموعة *',style:TextStyle(fontWeight:FontWeight.bold)),Container(decoration:BoxDecoration(border:Border.all(color:Colors.grey.shade300),borderRadius:BorderRadius.circular(8)),child:Column(children:students.map((x)=>CheckboxListTile(dense:true,controlAffinity:ListTileControlAffinity.leading,value:selected.contains(id(x)),title:Text('${x['name']}'),onChanged:(v)=>setD((){if(v==true)selected.add(id(x));else selected.remove(id(x));}))).toList())),if(selected.isNotEmpty)Text('تم اختيار ${selected.length} طالب/طلاب')])))),actions:[TextButton(onPressed:()=>Navigator.pop(dc,false),child:const Text('إلغاء')),FilledButton.icon(onPressed:(){if(form.currentState!.validate()&&selected.isNotEmpty)Navigator.pop(dc,true);},icon:const Icon(Icons.save),label:const Text('حفظ المجموعة'))]));}));
  if(ok==true){try{await ApiService.post('groups',{'name':name.text.trim(),'grade':grade.text.trim(),'subject':subject,'teacher_id':teacherId,'supervisor_id':supervisorId,'teacher_rate':double.tryParse(rate.text)??0,'student_ids':selected.toList(),'status':'active'});await load();}catch(e){msg(e);}}name.dispose();rate.dispose();grade.dispose();
 }
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('المجموعات'),actions:[IconButton(onPressed:load,icon:const Icon(Icons.refresh))]),floatingActionButton:FloatingActionButton.extended(onPressed:add,icon:const Icon(Icons.groups),label:const Text('إنشاء مجموعة')),body:loading?const Center(child:CircularProgressIndicator()):RefreshIndicator(onRefresh:load,child:ListView(padding:const EdgeInsets.fromLTRB(16,12,16,90),children:[Card(child:Padding(padding:const EdgeInsets.all(14),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('قبل إنشاء حصة جروب',style:TextStyle(fontWeight:FontWeight.bold,fontSize:17)),const SizedBox(height:4),const Text('1) أضف الطلاب  2) أضف المدرس  3) أنشئ المجموعة واختر الطلاب  4) اذهب إلى «الدروس والحصص» واختر «حصة جروب».')])),if(groups.isEmpty)const Padding(padding:EdgeInsets.all(30),child:Center(child:Text('لا توجد مجموعات بعد. اضغط «إنشاء مجموعة».'))),...groups.map((g)=>Card(child:ListTile(leading:const CircleAvatar(child:Icon(Icons.groups)),title:Text('${g['name']??''}',style:const TextStyle(fontWeight:FontWeight.bold)),subtitle:Text('المدرس: ${g['teacher']?['name']??''}\nالمادة: ${g['subject']??''} • الطلاب: ${g['students_count']??0} • سعر الحصة: ${g['teacher_rate']??0}'),isThreeLine:true)))]));
}
