import 'package:flutter/material.dart';
import '../../services/api_service.dart';

class SubscriptionsScreen extends StatefulWidget{const SubscriptionsScreen({super.key});@override State<SubscriptionsScreen> createState()=>_SubscriptionsScreenState();}
class _SubscriptionsScreenState extends State<SubscriptionsScreen>{
 List subscriptions=[],students=[];List<String> subjects=[];bool loading=true;static const fallback=['العربية','اللغة الإنجليزية','الرياضيات','العلوم','الدراسات الاجتماعية','Math','Science','English','Arabic','German','French','Spanish','Quran'];
 List<dynamic> list(dynamic x)=>x is List?List<dynamic>.from(x):(x is Map&&x['data'] is List?List<dynamic>.from(x['data']):[]);int id(dynamic x)=>int.tryParse('${x['id']}')??0;String sub(dynamic x)=>x is Map?'${x['subject']??x['name']??''}':'$x';void msg(Object e)=>ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString().replaceFirst('Exception: ',''))));
 @override void initState(){super.initState();load();}
 Future<void> load()async{try{final r=await Future.wait([ApiService.get('subscriptions'),ApiService.get('students'),ApiService.get('subjects')]);final ss=list(r[2]).map(sub).where((x)=>x.isNotEmpty).toSet().toList();if(mounted)setState((){subscriptions=list(r[0]);students=list(r[1]);subjects=ss.isEmpty?fallback:ss;loading=false;});}catch(e){if(mounted){setState(()=>loading=false);msg(e);}}}
 Future<void> form({dynamic item})async{if(students.isEmpty){msg(Exception('أضف طالبًا أولًا.'));return;}int studentId=id(item?['student']??{'id':item?['student_id']});String subject='${item?['subject']??subjects.first}';if(!subjects.contains(subject))subject=subjects.first;String status='${item?['status']??'active'}';final amount=TextEditingController(text:'${item?['amount']??''}'),start=TextEditingController(text:'${item?['starts_on']??DateTime.now().toIso8601String().substring(0,10)}'),end=TextEditingController(text:'${item?['ends_on']??DateTime.now().add(const Duration(days:30)).toIso8601String().substring(0,10)}');final key=GlobalKey<FormState>();final ok=await showDialog<bool>(context:context,builder:(dc)=>StatefulBuilder(builder:(c,set)=>AlertDialog(title:Text(item==null?'إضافة اشتراك':'تعديل الاشتراك'),content:Form(key:key,child:Column(mainAxisSize:MainAxisSize.min,children:[DropdownButtonFormField<int>(value:studentId,decoration:const InputDecoration(labelText:'الطالب *'),items:students.map((s)=>DropdownMenuItem<int>(value:id(s),child:Text('${s['name']}'))).toList(),onChanged:(v){if(v!=null)set(()=>studentId=v);}),DropdownButtonFormField<String>(value:subject,decoration:const InputDecoration(labelText:'المادة *'),items:subjects.map((s)=>DropdownMenuItem<String>(value:s,child:Text(s))).toList(),onChanged:(v){if(v!=null)set(()=>subject=v);}),TextFormField(controller:amount,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'المبلغ *'),validator:(v)=>double.tryParse(v??'')==null?'مبلغ غير صحيح':null),TextFormField(controller:start,decoration:const InputDecoration(labelText:'البداية YYYY-MM-DD')),TextFormField(controller:end,decoration:const InputDecoration(labelText:'النهاية YYYY-MM-DD')),DropdownButtonFormField<String>(value:status,decoration:const InputDecoration(labelText:'الحالة'),items:const[DropdownMenuItem(value:'active',child:Text('نشط')),DropdownMenuItem(value:'inactive',child:Text('غير نشط')),DropdownMenuItem(value:'expired',child:Text('منتهي'))],onChanged:(v){if(v!=null)set(()=>status=v);})])),actions:[TextButton(onPressed:()=>Navigator.pop(dc,false),child:const Text('إلغاء')),FilledButton(onPressed:(){if(key.currentState!.validate())Navigator.pop(dc,true);},child:const Text('حفظ'))])));if(ok==true){try{final body={'student_id':studentId,'subject':subject,'amount':double.parse(amount.text),'starts_on':start.text.trim(),'ends_on':end.text.trim(),'status':status};if(item==null)await ApiService.post('subscriptions',body);else await ApiService.put('subscriptions/${id(item)}',body);await load();}catch(e){msg(e);}}for(final c in[amount,start,end])c.dispose();}
 Future<void> remove(dynamic item)async{final ok=await showDialog<bool>(context:context,builder:(dc)=>AlertDialog(title:const Text('حذف الاشتراك'),content:const Text('هل تريد حذف هذا الاشتراك؟'),actions:[TextButton(onPressed:()=>Navigator.pop(dc,false),child:const Text('إلغاء')),FilledButton(onPressed:()=>Navigator.pop(dc,true),child:const Text('حذف'))]));if(ok==true){try{await ApiService.delete('subscriptions/${id(item)}');await load();}catch(e){msg(e);}}}
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('الاشتراكات'),actions:[IconButton(onPressed:load,icon:const Icon(Icons.refresh))]),floatingActionButton:FloatingActionButton.extended(onPressed:()=>form(),icon:const Icon(Icons.add),label:const Text('إضافة اشتراك')),body:loading?const Center(child:CircularProgressIndicator()):RefreshIndicator(onRefresh:load,child:ListView.builder(padding:const EdgeInsets.fromLTRB(16,12,16,90),itemCount:subscriptions.length,itemBuilder:(_,i){final s=subscriptions[i],student=s['student'];final payments=list(s['payments']);return Card(child:ListTile(leading:const CircleAvatar(child:Icon(Icons.event_available)),title:Text('${student?['name']??'طالب'}',style:const TextStyle(fontWeight:FontWeight.bold)),subtitle:Text('${s['subject']??''} • ${s['amount']??0}\n${s['starts_on']??''} → ${s['ends_on']??''} • ${s['status']??''}\nمدفوعات مرتبطة: ${payments.length}'),isThreeLine:true,trailing:Wrap(mainAxisSize:MainAxisSize.min,children:[IconButton(onPressed:()=>form(item:s),icon:const Icon(Icons.edit)),IconButton(onPressed:()=>remove(s),icon:const Icon(Icons.delete))])));}));
}
