import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../core/theme/app_theme.dart';
import '../../models/course_model.dart';
import '../../providers/courses_provider.dart';

class CoursesScreen extends StatelessWidget {
  const CoursesScreen({super.key});
  @override Widget build(BuildContext context) => ChangeNotifierProvider(create:(c)=>CoursesProvider(c.read())..load(), child: const _CoursesView());
}
class _CoursesView extends StatefulWidget { const _CoursesView(); @override State<_CoursesView> createState()=>_CoursesViewState(); }
class _CoursesViewState extends State<_CoursesView> {
  final search=TextEditingController();
  @override void dispose(){search.dispose();super.dispose();}
  @override Widget build(BuildContext context){
    final s=context.watch<CoursesProvider>();
    return Scaffold(appBar:AppBar(title:const Text('الكورسات والمواد'),actions:[IconButton(onPressed:s.loading?null:()=>s.load(query:search.text),icon:const Icon(Icons.refresh_rounded))]),
      floatingActionButton:FloatingActionButton.extended(onPressed:()=>_form(context),backgroundColor:AppTheme.primary,foregroundColor:Colors.white,icon:const Icon(Icons.add),label:const Text('إضافة كورس')),
      body:Column(children:[Padding(padding:const EdgeInsets.fromLTRB(16,12,16,8),child:TextField(controller:search,textInputAction:TextInputAction.search,onSubmitted:(_)=>s.load(query:search.text),decoration:InputDecoration(hintText:'ابحث باسم الكورس أو المادة',prefixIcon:const Icon(Icons.search),suffixIcon:search.text.isEmpty?null:IconButton(onPressed:(){search.clear();s.load();setState((){});},icon:const Icon(Icons.clear))))),
      Expanded(child:RefreshIndicator(onRefresh:()=>s.load(query:search.text),child:s.loading&&s.courses.isEmpty?const Center(child:CircularProgressIndicator()):s.error!=null&&s.courses.isEmpty?_Error(s.error!,()=>s.load(query:search.text)):s.courses.isEmpty?const _Empty():NotificationListener<ScrollNotification>(onNotification:(n){if(n.metrics.pixels>=n.metrics.maxScrollExtent-300&&s.hasMore&&!s.loading){s.page++;s.load(query:search.text,append:true);}return false;},child:ListView.separated(padding:const EdgeInsets.fromLTRB(16,8,16,100),itemCount:s.courses.length+(s.hasMore?1:0),separatorBuilder:(_,__)=>const SizedBox(height:8),itemBuilder:(_,i){if(i==s.courses.length)return const Padding(padding:EdgeInsets.all(16),child:Center(child:CircularProgressIndicator()));final c=s.courses[i];return _Card(course:c,onEdit:()=>_form(context,course:c),onDelete:()=>_delete(context,c));})))]) );
  }
  Future<void> _form(BuildContext context,{CourseModel? course})async{
    final name=TextEditingController(text:course?.name??''), subject=TextEditingController(text:course?.subject??''), level=TextEditingController(text:course?.level??''), price=TextEditingController(text:course?.price==0?'':course!.price.toString()), desc=TextEditingController(text:course?.description??'');
    final key=GlobalKey<FormState>();
    await showModalBottomSheet(context:context,isScrollControlled:true,showDragHandle:true,builder:(sheet)=>Padding(padding:EdgeInsets.fromLTRB(20,8,20,MediaQuery.of(sheet).viewInsets.bottom+20),child:Form(key:key,child:SingleChildScrollView(child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[Text(course==null?'إضافة كورس':'تعديل الكورس',style:const TextStyle(fontSize:20,fontWeight:FontWeight.w900)),const SizedBox(height:18),_field(name,'اسم الكورس',Icons.menu_book_outlined,true),_field(subject,'المادة',Icons.book_outlined,false),_field(level,'المرحلة / الصف',Icons.school_outlined,false),_field(price,'السعر',Icons.payments_outlined,false),_field(desc,'الوصف',Icons.notes_outlined,false,maxLines:3),const SizedBox(height:18),FilledButton.icon(onPressed:()async{if(!key.currentState!.validate())return;final ok=await context.read<CoursesProvider>().save(id:course?.id,data:{'name':name.text.trim(),'subject':subject.text.trim(),'level':level.text.trim(),'price':num.tryParse(price.text.trim())??0,'description':desc.text.trim()});if(ok&&sheet.mounted)Navigator.pop(sheet);},icon:const Icon(Icons.save_outlined),label:const Text('حفظ'))]))));
    for(final c in [name,subject,level,price,desc])c.dispose();
  }
  Widget _field(TextEditingController c,String label,IconData icon,bool required,{int maxLines=1})=>Padding(padding:const EdgeInsets.only(bottom:12),child:TextFormField(controller:c,maxLines:maxLines,keyboardType:label=='السعر'?TextInputType.number:null,decoration:InputDecoration(labelText:label,prefixIcon:Icon(icon)),validator:required?(v)=>(v==null||v.trim().isEmpty)?'هذا الحقل مطلوب':null:null));
  Future<void> _delete(BuildContext context,CourseModel c)async{final yes=await showDialog<bool>(context:context,builder:(d)=>AlertDialog(title:const Text('حذف الكورس'),content:Text('هل تريد حذف ${c.name}؟'),actions:[TextButton(onPressed:()=>Navigator.pop(d,false),child:const Text('إلغاء')),FilledButton(onPressed:()=>Navigator.pop(d,true),child:const Text('حذف'))]));if(yes==true&&context.mounted){final ok=await context.read<CoursesProvider>().remove(c.id);if(!ok&&context.mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(context.read<CoursesProvider>().error??'تعذر الحذف')));}}
}
class _Card extends StatelessWidget{final CourseModel course;final VoidCallback onEdit,onDelete;const _Card({required this.course,required this.onEdit,required this.onDelete});@override Widget build(BuildContext context)=>Card(child:ListTile(contentPadding:const EdgeInsets.symmetric(horizontal:14,vertical:8),leading:CircleAvatar(radius:26,backgroundColor:const Color(0xFFFFE8EA),child:const Icon(Icons.menu_book,color:AppTheme.primary)),title:Text(course.name.isEmpty?'بدون اسم':course.name,style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Padding(padding:const EdgeInsets.only(top:5),child:Text([course.subject,course.level,course.price>0?'${course.price} جنيه':''].where((x)=>x.isNotEmpty).join(' • '),maxLines:2,overflow:TextOverflow.ellipsis)),trailing:PopupMenuButton<String>(onSelected:(v){if(v=='edit')onEdit();else onDelete();},itemBuilder:(_)=>const[PopupMenuItem(value:'edit',child:Text('تعديل')),PopupMenuItem(value:'delete',child:Text('حذف'))])));}
class _Empty extends StatelessWidget{const _Empty();@override Widget build(BuildContext c)=>ListView(children:const[SizedBox(height:100),Icon(Icons.menu_book_outlined,size:60,color:Colors.grey),SizedBox(height:12),Center(child:Text('لا توجد كورسات'))]);}
class _Error extends StatelessWidget{final String m;final VoidCallback r;const _Error(this.m,this.r);@override Widget build(BuildContext c)=>ListView(children:[const SizedBox(height:100),const Icon(Icons.cloud_off_outlined,size:52),const SizedBox(height:10),Center(child:Text(m)),TextButton(onPressed:r,child:const Text('إعادة المحاولة'))]);}
