import 'package:flutter/material.dart';
import '../../core/theme/app_theme.dart';
import '../../services/api_service.dart';

class StudentsScreen extends StatefulWidget{const StudentsScreen({super.key});@override State<StudentsScreen> createState()=>_StudentsScreenState();}
class _StudentsScreenState extends State<StudentsScreen>{
 List students=[],subjects=[];bool loading=true;
 List<dynamic> asList(dynamic v)=>v is List?List<dynamic>.from(v):v is Map&&v['data'] is List?List<dynamic>.from(v['data']):[];
 @override void initState(){super.initState();load();}
 void msg(Object e)=>ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString().replaceFirst('Exception: ',''))));
 Future<void> load()async{try{final a=await ApiService.get('students');final b=await ApiService.get('subjects');if(!mounted)return;setState((){students=asList(a);subjects=asList(b);loading=false;});}catch(e){if(mounted){setState(()=>loading=false);msg(e);}}}
 Future<void> add()async{final name=TextEditingController(),phone=TextEditingController(),parent=TextEditingController(),parentPhone=TextEditingController(),grade=TextEditingController(),curr=TextEditingController();final selected=<String>{};final form=GlobalKey<FormState>();final ok=await showDialog<bool>(context:context,builder:(c){return StatefulBuilder(builder:(c,setD){return AlertDialog(title:const Text('إضافة طالب'),content:SingleChildScrollView(child:Form(key:form,child:Column(children:[TextFormField(controller:name,decoration:const InputDecoration(labelText:'اسم الطالب *'),validator:(v)=>v==null||v.trim().isEmpty?'مطلوب':null),TextFormField(controller:phone,decoration:const InputDecoration(labelText:'هاتف الطالب')),TextFormField(controller:parent,decoration:const InputDecoration(labelText:'اسم ولي الأمر')),TextFormField(controller:parentPhone,decoration:const InputDecoration(labelText:'هاتف ولي الأمر')),TextFormField(controller:grade,decoration:const InputDecoration(labelText:'الصف')),TextFormField(controller:curr,decoration:const InputDecoration(labelText:'المنهج')),const SizedBox(height:10),const Align(alignment:Alignment.centerRight,child:Text('المواد المشترك بها',style:TextStyle(fontWeight:FontWeight.bold))),...subjects.map((s){final v='$s';return CheckboxListTile(dense:true,value:selected.contains(v),title:Text(v),onChanged:(x){setD((){if(x==true){selected.add(v);}else{selected.remove(v);}});});})])),),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('إلغاء')),FilledButton(onPressed:(){if(form.currentState!.validate())Navigator.pop(c,true);},child:const Text('حفظ'))]);});});if(ok==true){try{await ApiService.post('students',{'name':name.text.trim(),'phone':phone.text.trim(),'parent_name':parent.text.trim(),'parent_phone':parentPhone.text.trim(),'grade':grade.text.trim(),'curriculum':curr.text.trim(),'status':'active','subjects':selected.toList()});await load();}catch(e){msg(e);}}for(final x in[name,phone,parent,parentPhone,grade,curr]){x.dispose();}}
 Future<void> details(dynamic id)async{try{final r=await ApiService.get('students/$id');final d=Map<String,dynamic>.from(r is Map&&r['data'] is Map?r['data']:r);if(!mounted)return;final fields=[['المواد',asList(d['subjects'])],['المدرسون',asList(d['teachers'])],['المجموعات',asList(d['groups'])],['الحصص',asList(d['lessons'])],['الاشتراكات',asList(d['subscriptions'])],['المدفوعات',asList(d['payments'])]];await showDialog(context:context,builder:(c){return AlertDialog(title:Text('${d['name']??'الطالب'}'),content:SizedBox(width:500,child:SingleChildScrollView(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[for(final f in fields)Padding(padding:const EdgeInsets.only(bottom:10),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('${f[0]}',style:const TextStyle(fontWeight:FontWeight.bold)),if((f[1] as List).isEmpty)const Text('لا يوجد'),...(f[1] as List).map((x)=>Text('• ${x is Map?(x['name']??x['subject']??x['amount']??x):x}'))]))])),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('إغلاق'))]);});}catch(e){msg(e);}}
 @override Widget build(BuildContext context){return Scaffold(appBar:AppBar(title:const Text('الطلاب'),actions:[IconButton(onPressed:load,icon:const Icon(Icons.refresh))]),floatingActionButton:FloatingActionButton(onPressed:add,backgroundColor:AppColors.red,child:const Icon(Icons.add)),body:loading?const Center(child:CircularProgressIndicator()):RefreshIndicator(onRefresh:load,child:ListView.builder(padding:const EdgeInsets.all(16),itemCount:students.length,itemBuilder:(c,i){final s=students[i];return Card(child:ListTile(onTap:()=>details(s['id']),title:Text('${s['name']??''}',style:const TextStyle(fontWeight:FontWeight.bold)),subtitle:Text('${s['phone']??''}'),trailing:const Icon(Icons.chevron_left)));})));
 }
}
