import 'package:flutter/material.dart';
import '../../services/api_service.dart';

class FinanceScreen extends StatefulWidget { const FinanceScreen({super.key}); @override State<FinanceScreen> createState()=>_FinanceScreenState(); }
class _FinanceScreenState extends State<FinanceScreen>{Map<String,dynamic> summary={};List teachers=[],supervisors=[],withdrawals=[];bool loading=true;String? error;@override void initState(){super.initState();load();}
Future<void> load()async{try{final r=await Future.wait([ApiService.get('finance/summary'),ApiService.get('teachers'),ApiService.get('supervisors'),ApiService.get('finance/withdrawals')]);if(mounted)setState((){summary=r[0]['data']??{};teachers=r[1]['data']??[];supervisors=r[2]['data']??[];withdrawals=r[3]['data']??[];loading=false;error=null;});}catch(e){if(mounted)setState((){loading=false;error=e.toString().replaceFirst('Exception: ','');});}}
Future<void> payDue(String type,int id,double max)async{final amount=TextEditingController(text:max.toStringAsFixed(2));final ok=await showDialog<bool>(context:context,builder:(c)=>AlertDialog(title:const Text('صرف مستحق'),content:TextField(controller:amount,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:InputDecoration(labelText:'المبلغ',helperText:'المتاح $max')),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('إلغاء')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('صرف'))]));if(ok!=true)return;try{final x=double.parse(amount.text);if(x<=0||x>max)throw Exception('المبلغ غير صحيح');await ApiService.post('finance/dues/$type/$id/pay',{'amount':x});await load();_msg('تم تسجيل الصرف');}catch(e){_msg(e.toString().replaceFirst('Exception: ',''));}}
Future<void> withdraw()async{final type=ValueNotifier<String>('teacher');int? id=teachers.isEmpty?null:teachers.first['id'];final amount=TextEditingController();final notes=TextEditingController();final key=GlobalKey<FormState>();final ok=await showDialog<bool>(context:context,builder:(c)=>StatefulBuilder(builder:(c,setD)=>AlertDialog(title:const Text('طلب سحب'),content:Form(key:key,child:Column(mainAxisSize:MainAxisSize.min,children:[ValueListenableBuilder<String>(valueListenable:type,builder:(_,v,__)= >DropdownButtonFormField<String>(value:v,items:const [DropdownMenuItem(value:'teacher',child:Text('مدرس')),DropdownMenuItem(value:'supervisor',child:Text('مشرف'))],onChanged:(x){if(x!=null){type.value=x;id=x=='teacher'?(teachers.isEmpty?null:teachers.first['id']):(supervisors.isEmpty?null:supervisors.first['id']);setD((){});}},decoration:const InputDecoration(labelText:'النوع'))),if((type.value=='teacher'?teachers:supervisors).isNotEmpty)DropdownButtonFormField<int>(value:id,items:(type.value=='teacher'?teachers:supervisors).map((x)=>DropdownMenuItem<int>(value:x['id'],child:Text('${x['name']??''}'))).toList(),onChanged:(x){if(x!=null)setD(()=>id=x);},decoration:const InputDecoration(labelText:'المستحق')),TextFormField(controller:amount,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'المبلغ'),validator:(v)=>double.tryParse(v??'')==null?'أدخل مبلغًا صحيحًا':null),TextFormField(controller:notes,decoration:const InputDecoration(labelText:'ملاحظات'))])),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('إلغاء')),FilledButton(onPressed:(){if(key.currentState!.validate()&&id!=null)Navigator.pop(c,true);},child:const Text('إرسال'))]));if(ok!=true||id==null)return;try{await ApiService.post('finance/withdrawals',{'recipient_type':type.value,'recipient_id':id,'amount':double.parse(amount.text),'notes':notes.text.trim()});await load();_msg('تم إنشاء طلب السحب');}catch(e){_msg(e.toString().replaceFirst('Exception: ',''));}}
Future<void> updateWithdrawal(int id,String status)async{try{await ApiService.post('finance/withdrawals/$id',{'status':status});await load();}catch(e){_msg(e.toString().replaceFirst('Exception: ',''));}}
void _msg(String x){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(x)));}
@override Widget build(BuildContext context){if(loading)return Scaffold(appBar:AppBar(title:const Text('المالية والمستحقات')),body:const Center(child:CircularProgressIndicator()));if(error!=null)return Scaffold(appBar:AppBar(title:const Text('المالية والمستحقات')),body:Center(child:Text(error!)));return Scaffold(appBar:AppBar(title:const Text('المالية والمستحقات'),actions:[IconButton(onPressed:load,icon:const Icon(Icons.refresh))]),floatingActionButton:FloatingActionButton(onPressed:withdraw,child:const Icon(Icons.request_page)),body:RefreshIndicator(onRefresh:load,child:ListView(padding:const EdgeInsets.all(16),children:[_card('مستحقات المدرسين',summary['teacher_due']),_card('مدفوع للمدرسين',summary['teacher_paid']),_card('متبقي للمدرسين',summary['teacher_remaining']),_card('مستحقات المشرفين',summary['supervisor_due']),_card('مدفوع للمشرفين',summary['supervisor_paid']),_card('متبقي للمشرفين',summary['supervisor_remaining']),const SizedBox(height:12),const Text('طلبات السحب',style:TextStyle(fontSize:20,fontWeight:FontWeight.bold)),...withdrawals.map((w)=>Card(child:ListTile(title:Text('${w['recipient_type']=='teacher'?'مدرس':'مشرف'} #${w['recipient_id']}'),subtitle:Text('المبلغ: ${w['amount']} • الحالة: ${w['status']}'),trailing:w['status']=='pending'?PopupMenuButton<String>(onSelected:(s)=>updateWithdrawal(w['id'],s),itemBuilder:(_)=>const [PopupMenuItem(value:'approved',child:Text('اعتماد')),PopupMenuItem(value:'rejected',child:Text('رفض'))]):w['status']=='approved'?TextButton(onPressed:()=>updateWithdrawal(w['id'],'paid'),child:const Text('تم الصرف')):null))),const SizedBox(height:12),const Text('ملاحظة: صرف المستحقات يجب أن ينعكس أيضًا في التدفق النقدي.',style:TextStyle(fontWeight:FontWeight.bold))])));}
Widget _card(String t,dynamic v)=>Card(child:ListTile(title:Text(t),trailing:Text('${v??0}',style:const TextStyle(fontSize:18,fontWeight:FontWeight.bold))));
}
