import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../core/theme/app_theme.dart';
import '../../providers/reports_provider.dart';
class ReportsScreen extends StatelessWidget { const ReportsScreen({super.key});
 @override Widget build(BuildContext context)=>ChangeNotifierProvider(create:(c)=>ReportsProvider(c.read())..load(),child:const _View()); }
class _View extends StatelessWidget { const _View();
 @override Widget build(BuildContext context){ final p=context.watch<ReportsProvider>(); return Scaffold(appBar:AppBar(title:const Text('التقارير'),actions:[IconButton(onPressed:p.loading?null:()=>p.load(),icon:const Icon(Icons.refresh))]),body:RefreshIndicator(onRefresh:p.load,child:ListView(padding:const EdgeInsets.all(16),children:[_Period(p),if(p.error!=null)_Error(p.error!,p.load),if(p.loading&&p.data==const ReportSummary())const Padding(padding:EdgeInsets.all(30),child:Center(child:CircularProgressIndicator())),_Financial(p.data),const SizedBox(height:14),_Attendance(p.data),const SizedBox(height:14),_Counts(p.data),if(p.data.items.isNotEmpty)...[const SizedBox(height:18),const Text('تفاصيل التقرير',style:TextStyle(fontSize:18,fontWeight:FontWeight.w800)),const SizedBox(height:8),...p.data.items.map((x)=>Card(child:ListTile(title:Text(x.label),trailing:Text(x.value,style:const TextStyle(fontWeight:FontWeight.w800,color:AppTheme.primary)))))] ]))); }
}
class _Period extends StatelessWidget { final ReportsProvider p; const _Period(this.p); @override Widget build(BuildContext c)=>Card(child:Padding(padding:const EdgeInsets.symmetric(horizontal:12),child:DropdownButtonHideUnderline(child:DropdownButton<String>(value:p.period,isExpanded:true,items:const [DropdownMenuItem(value:'day',child:Text('اليوم')),DropdownMenuItem(value:'week',child:Text('هذا الأسبوع')),DropdownMenuItem(value:'month',child:Text('هذا الشهر')),DropdownMenuItem(value:'year',child:Text('هذا العام'))],onChanged:(v){if(v!=null)p.setPeriod(v);}))))); }
class _Financial extends StatelessWidget { final dynamic d; const _Financial(this.d); @override Widget build(BuildContext c)=>Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('الماليات',style:TextStyle(fontSize:18,fontWeight:FontWeight.w800)),const SizedBox(height:12),Row(children:[_Metric('الإيرادات',d.revenue),_Metric('المحصّل',d.collected),_Metric('المتبقي',d.outstanding)]),])); }
class _Metric extends StatelessWidget { final String label; final double value; const _Metric(this.label,this.value); @override Widget build(BuildContext c)=>Expanded(child:Column(children:[Text(value.toStringAsFixed(2),style:const TextStyle(fontSize:18,fontWeight:FontWeight.w900,color:AppTheme.primary)),const SizedBox(height:4),Text(label,style:TextStyle(color:Colors.grey.shade600))])); }
class _Attendance extends StatelessWidget { final dynamic d; const _Attendance(this.d); @override Widget build(BuildContext c)=>Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('الحضور',style:TextStyle(fontSize:18,fontWeight:FontWeight.w800)),const SizedBox(height:14),Row(children:[_A('حاضر',d.present,Colors.green),_A('غائب',d.absent,AppTheme.primary),_A('متأخر',d.late,Colors.orange),_A('معتذر',d.excused,Colors.blueGrey)]),])); }
class _A extends StatelessWidget { final String l; final int v; final Color c; const _A(this.l,this.v,this.c); @override Widget build(BuildContext x)=>Expanded(child:Column(children:[CircleAvatar(radius:24,backgroundColor:c.withOpacity(.12),child:Text('$v',style:TextStyle(color:c,fontWeight:FontWeight.w900))),const SizedBox(height:6),Text(l)])); }
class _Counts extends StatelessWidget { final dynamic d; const _Counts(this.d); @override Widget build(BuildContext c)=>GridView.count(shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),crossAxisCount:2,childAspectRatio:2.2,crossAxisSpacing:10,mainAxisSpacing:10,children:[_C('الطلاب',d.students,Icons.groups),_C('المدرسون',d.teachers,Icons.person),_C('الكورسات',d.courses,Icons.menu_book),_C('المجموعات',d.groups,Icons.class_),_C('الاشتراكات النشطة',d.activeSubscriptions,Icons.card_membership)]); }
class _C extends StatelessWidget { final String l; final int v; final IconData i; const _C(this.l,this.v,this.i); @override Widget build(BuildContext c)=>Card(child:ListTile(leading:Icon(i,color:AppTheme.primary),title:Text('$v',style:const TextStyle(fontWeight:FontWeight.w900,fontSize:20)),subtitle:Text(l))); }
class _Error extends StatelessWidget { final String m; final VoidCallback r; const _Error(this.m,this.r); @override Widget build(BuildContext c)=>Card(color:const Color(0xfffff3f3),child:ListTile(leading:const Icon(Icons.error_outline,color:AppTheme.primary),title:Text(m),trailing:TextButton(onPressed:r,child:const Text('إعادة')))); }
