<?php
namespace App\Http\Controllers;
use App\Models\{Student,StudentSubject,StudentEvaluation,StudentResource};
use Illuminate\Http\Request;
class AcademicTrackingController extends Controller
{
 public function plans(Request $request){$q=StudentSubject::with('student')->orderBy('student_id')->orderBy('subject');if($request->filled('student_id'))$q->where('student_id',$request->integer('student_id'));return ['success'=>true,'data'=>$q->get()];}
 public function updatePlan(Request $request, StudentSubject $studentSubject){$d=$request->validate(['monthly_lessons'=>'required|integer|min:0|max:500','completed_lessons'=>'nullable|integer|min:0|max:500','plan_month'=>'required|date_format:Y-m']);$completed=(int)($d['completed_lessons']??$studentSubject->completed_lessons??0);if($completed>$d['monthly_lessons'])return response()->json(['message'=>'الحصص المنفذة لا يمكن أن تتجاوز الحصص الشهرية.'],422);$studentSubject->update([...$d,'completed_lessons'=>$completed]);return ['success'=>true,'data'=>$studentSubject->fresh()->load('student')];}
 public function evaluations(Request $request){$q=StudentEvaluation::with(['student','teacher','supervisor','lesson'])->latest('evaluation_date')->latest('id');if($request->filled('student_id'))$q->where('student_id',$request->integer('student_id'));if($request->filled('teacher_id'))$q->where('teacher_id',$request->integer('teacher_id'));return ['success'=>true,'data'=>$q->paginate(100)];}
 public function storeEvaluation(Request $request){$d=$request->validate(['student_id'=>'required|exists:students,id','teacher_id'=>'nullable|exists:teachers,id','supervisor_id'=>'nullable|exists:supervisors,id','lesson_id'=>'nullable|exists:lessons,id','subject'=>'nullable|string|max:150','score'=>'nullable|numeric|min:0|max:100','title'=>'nullable|string|max:255','notes'=>'nullable|string','evaluation_date'=>'required|date']);return response()->json(['success'=>true,'data'=>StudentEvaluation::create($d)->load(['student','teacher','supervisor','lesson'])],201);}
 public function updateEvaluation(Request $request, StudentEvaluation $evaluation){$evaluation->update($request->validate(['teacher_id'=>'nullable|exists:teachers,id','supervisor_id'=>'nullable|exists:supervisors,id','lesson_id'=>'nullable|exists:lessons,id','subject'=>'nullable|string|max:150','score'=>'nullable|numeric|min:0|max:100','title'=>'nullable|string|max:255','notes'=>'nullable|string','evaluation_date'=>'sometimes|date']));return ['success'=>true,'data'=>$evaluation->fresh()->load(['student','teacher','supervisor','lesson'])];}
 public function destroyEvaluation(StudentEvaluation $evaluation){$evaluation->delete();return ['success'=>true];}
 public function resources(Request $request){$q=StudentResource::with(['student','teacher','lesson'])->latest('id');if($request->filled('student_id'))$q->where('student_id',$request->integer('student_id'));if($request->filled('teacher_id'))$q->where('teacher_id',$request->integer('teacher_id'));return ['success'=>true,'data'=>$q->paginate(100)];}
 public function storeResource(Request $request){$d=$request->validate(['student_id'=>'required|exists:students,id','teacher_id'=>'nullable|exists:teachers,id','lesson_id'=>'nullable|exists:lessons,id','type'=>'required|in:link,video,web,homework,exam,file','title'=>'required|string|max:255','url'=>'nullable|url|max:2048','description'=>'nullable|string','published_on'=>'nullable|date']);return response()->json(['success'=>true,'data'=>StudentResource::create($d)->load(['student','teacher','lesson'])],201);}
 public function updateResource(Request $request, StudentResource $resource){$resource->update($request->validate(['teacher_id'=>'nullable|exists:teachers,id','lesson_id'=>'nullable|exists:lessons,id','type'=>'sometimes|in:link,video,web,homework,exam,file','title'=>'sometimes|required|string|max:255','url'=>'nullable|url|max:2048','description'=>'nullable|string','published_on'=>'nullable|date']));return ['success'=>true,'data'=>$resource->fresh()->load(['student','teacher','lesson'])];}
 public function destroyResource(StudentResource $resource){$resource->delete();return ['success'=>true];}
 public function studentTracking(Student $student){$subjects=$student->subjects()->get();$rows=$subjects->map(fn($s)=>['id'=>$s->id,'subject'=>$s->subject,'monthly_lessons'=>$s->monthly_lessons,'completed_lessons'=>$s->completed_lessons,'remaining'=>max(0,(int)($s->monthly_lessons??0)-(int)($s->completed_lessons??0)),'completion_percent'=>($s->monthly_lessons??0)>0?round(($s->completed_lessons/$s->monthly_lessons)*100,1):0]);return ['success'=>true,'data'=>['student'=>$student->load(['teachers','groups','lessons.teacher','subscriptions.payments','payments.subscription']),'plans'=>$rows,'evaluations'=>$student->evaluations()->with(['teacher','supervisor','lesson'])->latest('evaluation_date')->get(),'resources'=>$student->resources()->with(['teacher','lesson'])->latest()->get()]];}
}
