<?php
namespace App\Http\Controllers;
use App\Models\{User,Student,Teacher,Schedule,Attendance,Subscription,Payment,Expense,TeacherDue};
use Illuminate\Http\Request; use Illuminate\Support\Facades\Hash; use Illuminate\Validation\Rule;
class ApiController extends Controller {
 public function login(Request $r){$d=$r->validate(['email'=>'required|email','password'=>'required']);$u=User::where('email',$d['email'])->first();abort_unless($u&&Hash::check($d['password'],$u->password),401,'Invalid credentials');return ['token'=>$u->createToken('management')->plainTextToken,'user'=>$u];}
 public function logout(Request $r){$r->user()->currentAccessToken()?->delete();return ['message'=>'Logged out'];}
 public function dashboard(){return ['students'=>Student::count(),'active_students'=>Student::where('status','active')->count(),'teachers'=>Teacher::where('status','active')->count(),'today_classes'=>Schedule::whereDate('starts_at',now())->count(),'today_attendance'=>Attendance::whereDate('date',today())->count(),'monthly_income'=>Payment::whereBetween('paid_on',[now()->startOfMonth(),now()->endOfMonth()])->sum('amount'),'monthly_expenses'=>Expense::whereBetween('spent_on',[now()->startOfMonth(),now()->endOfMonth()])->sum('amount'),'expiring_7_days'=>Subscription::whereBetween('ends_on',[today(),today()->addDays(7)])->where('status','active')->count()];}
 public function index(){return Student::latest()->paginate(25);} public function store(Request $r){return Student::create($r->validate(['name'=>'required','phone'=>'nullable','parent_name'=>'nullable','parent_phone'=>'nullable','email'=>'nullable|email','grade'=>'nullable','curriculum'=>'nullable','status'=>'nullable','notes'=>'nullable']));} public function show(Student $student){return $student;} public function update(Request $r,Student $student){$student->update($r->all());return $student;} public function destroy(Student $student){$student->delete();return response()->noContent();}
 public function teachers(){return Teacher::latest()->paginate(25);} public function storeTeacher(Request $r){return Teacher::create($r->validate(['name'=>'required','phone'=>'nullable','email'=>'nullable|email','specialization'=>'nullable','hourly_rate'=>'nullable|numeric','status'=>'nullable']));}
 public function schedules(){return Schedule::with(['teacher','student'])->orderBy('starts_at')->paginate(50);} public function storeSchedule(Request $r){$d=$r->validate(['teacher_id'=>'required|exists:teachers,id','student_id'=>'nullable|exists:students,id','group_name'=>'nullable','subject'=>'required','starts_at'=>'required|date','ends_at'=>'required|date|after:starts_at','zoom_url'=>'nullable|url']);$conflict=Schedule::where('teacher_id',$d['teacher_id'])->where(function($q)use($d){$q->whereBetween('starts_at',[$d['starts_at'],$d['ends_at']])->orWhereBetween('ends_at',[$d['starts_at'],$d['ends_at']]);})->exists();abort_if($conflict,422,'Teacher schedule conflict');return Schedule::create($d);}
 public function attendance(){return Attendance::latest('date')->paginate(100);} public function storeAttendance(Request $r){$d=$r->validate(['student_id'=>'required|exists:students,id','teacher_id'=>'nullable|exists:teachers,id','schedule_id'=>'nullable|exists:schedules,id','date'=>'required|date','status'=>['required',Rule::in(['present','absent','late','excused'])],'notes'=>'nullable']);$d['marked_at']=now();return Attendance::create($d);}
 public function subscriptions(){return Subscription::with('student')->latest()->paginate(50);} public function storeSubscription(Request $r){return Subscription::create($r->validate(['student_id'=>'required|exists:students,id','subject'=>'required','amount'=>'required|numeric','starts_on'=>'required|date','ends_on'=>'required|date|after_or_equal:starts_on','status'=>'nullable']));}
 public function payments(){return Payment::latest('paid_on')->paginate(50);} public function storePayment(Request $r){return Payment::create($r->validate(['student_id'=>'required|exists:students,id','subscription_id'=>'nullable|exists:subscriptions,id','amount'=>'required|numeric','paid_on'=>'required|date','method'=>'nullable','collector'=>'nullable','reference'=>'nullable','notes'=>'nullable']));}
 public function expenses(){return Expense::latest('spent_on')->paginate(50);} public function storeExpense(Request $r){return Expense::create($r->validate(['category'=>'required','amount'=>'required|numeric','spent_on'=>'required|date','description'=>'nullable']));}
 public function teacherDues(){return TeacherDue::with('teacher')->latest()->paginate(50);} public function financialReport(){return ['income'=>Payment::sum('amount'),'expenses'=>Expense::sum('amount'),'teacher_dues'=>TeacherDue::sum('amount'),'teacher_paid'=>TeacherDue::sum('paid_amount')];}
}
