<?php
namespace App\Http\Controllers;
use App\Models\Bonus; use App\Models\Expense; use App\Models\SupervisorDue; use App\Models\TeacherLessonDue; use App\Models\WithdrawalRequest; use App\Models\WithdrawalSetting; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB; use Illuminate\Validation\Rule;
class FinanceController{
public function teacherDues(Request $r){$q=TeacherLessonDue::with(['teacher','lesson'])->latest();if($r->filled('teacher_id'))$q->where('teacher_id',$r->integer('teacher_id'));if($r->filled('status'))$q->where('status',$r->string('status'));return response()->json(['success'=>true,'data'=>$q->get()]);}
public function supervisorDues(Request $r){$q=SupervisorDue::with(['supervisor','lesson'])->latest();if($r->filled('supervisor_id'))$q->where('supervisor_id',$r->integer('supervisor_id'));if($r->filled('status'))$q->where('status',$r->string('status'));return response()->json(['success'=>true,'data'=>$q->get()]);}
public function bonuses(Request $r){$q=Bonus::latest();if($r->filled('recipient_type'))$q->where('recipient_type',$r->string('recipient_type'));if($r->filled('recipient_id'))$q->where('recipient_id',$r->integer('recipient_id'));return response()->json(['success'=>true,'data'=>$q->get()]);}
public function storeBonus(Request $r){$d=$r->validate(['recipient_type'=>['required',Rule::in(['teacher','supervisor'])],'recipient_id'=>'required|integer','name'=>'required|string|max:255','amount'=>'required|numeric|min:0.01','bonus_date'=>'required|date','notes'=>'nullable|string']);$d['created_by']=$r->user()->id;return DB::transaction(function()use($d){$bonus=Bonus::create($d);Expense::create(['category'=>$d['recipient_type']==='teacher'?'مكافأة مدرس':'مكافأة مشرف','amount'=>$d['amount'],'spent_on'=>$d['bonus_date'],'description'=>'مكافأة: '.$d['name'],'created_by'=>$d['created_by']]);return response()->json(['success'=>true,'data'=>$bonus],201);});}
public function withdrawalSettings(){return response()->json(['success'=>true,'data'=>WithdrawalSetting::all()]);}
public function updateWithdrawalSetting(Request $r){$d=$r->validate(['recipient_type'=>['required',Rule::in(['teacher','supervisor'])],'enabled'=>'required|boolean','minimum_amount'=>'required|numeric|min:0']);return response()->json(['success'=>true,'data'=>WithdrawalSetting::updateOrCreate(['recipient_type'=>$d['recipient_type']],['enabled'=>$d['enabled'],'minimum_amount'=>$d['minimum_amount']])]);}
public function withdrawals(Request $r){$q=WithdrawalRequest::latest();foreach(['recipient_type','status'] as $f)if($r->filled($f))$q->where($f,$r->string($f));if($r->filled('recipient_id'))$q->where('recipient_id',$r->integer('recipient_id'));return response()->json(['success'=>true,'data'=>$q->get()]);}
public function storeWithdrawal(Request $r){$d=$r->validate(['recipient_type'=>['required',Rule::in(['teacher','supervisor'])],'recipient_id'=>'required|integer','amount'=>'required|numeric|min:0.01','notes'=>'nullable|string']);$s=WithdrawalSetting::where('recipient_type',$d['recipient_type'])->first();if($s&&!$s->enabled)return response()->json(['success'=>false,'message'=>'السحب مغلق حاليًا.'],422);if($s&&$d['amount']<$s->minimum_amount)return response()->json(['success'=>false,'message'=>'المبلغ أقل من الحد الأدنى للسحب.'],422);$available=$this->availableBalance($d['recipient_type'],(int)$d['recipient_id']);if($d['amount']>$available)return response()->json(['success'=>false,'message'=>'المبلغ المطلوب أكبر من المستحق المتاح.'],422);$duplicate=WithdrawalRequest::where('recipient_type',$d['recipient_type'])->where('recipient_id',$d['recipient_id'])->whereIn('status',['pending','approved'])->exists();if($duplicate)return response()->json(['success'=>false,'message'=>'يوجد طلب سحب مفتوح بالفعل لهذا المستحق.'],422);return response()->json(['success'=>true,'data'=>WithdrawalRequest::create($d+['status'=>'pending'])],201);}
public function updateWithdrawal(Request $r,WithdrawalRequest $w){$d=$r->validate(['status'=>['required',Rule::in(['pending','approved','rejected','paid'])],'notes'=>'nullable|string']);if($w->status==='paid')return response()->json(['success'=>false,'message'=>'لا يمكن تعديل طلب تم صرفه.'],422);if($d['status']==='paid'&&$w->status!=='approved')return response()->json(['success'=>false,'message'=>'يجب اعتماد الطلب أولًا.'],422);DB::transaction(function()use($r,$w,$d){if($d['status']==='paid'){$this->applyPayment($w->recipient_type,(int)$w->recipient_id,(float)$w->amount);$w->paid_at=now();Expense::create(['category'=>$w->recipient_type==='teacher'?'صرف مستحق مدرس':'صرف مستحق مشرف','amount'=>$w->amount,'spent_on'=>today()->toDateString(),'description'=>'صرف طلب مستحق رقم '.$w->id,'created_by'=>$r->user()->id]);}$w->status=$d['status'];if($d['status']==='approved'){$w->approved_by=$r->user()->id;$w->approved_at=now();}if(array_key_exists('notes',$d))$w->notes=$d['notes'];$w->save();});return response()->json(['success'=>true,'data'=>$w->fresh()]);}
public function payDue(Request $r,string $type,int $due){$amount=$r->validate(['amount'=>'required|numeric|min:0.01'])['amount'];if(!in_array($type,['teacher','supervisor'],true))return response()->json(['message'=>'نوع المستحق غير صحيح.'],422);$model=$type==='teacher'?TeacherLessonDue::class:SupervisorDue::class;$record=$model::with('lesson')->findOrFail($due);if($record->lesson&&$record->lesson->status==='cancelled')return response()->json(['message'=>'لا يمكن صرف مستحق حصة ملغاة.'],422);$remaining=max(0,(float)$record->amount-(float)$record->paid_amount);if($amount>$remaining)return response()->json(['message'=>'المبلغ أكبر من المتبقي على المستحق.'],422);DB::transaction(function()use($record,$amount,$type,$r){$record->paid_amount=(float)$record->paid_amount+(float)$amount;$record->status=(float)$record->paid_amount>=(float)$record->amount?'paid':'partial';$record->save();Expense::create(['category'=>$type==='teacher'?'صرف مستحق مدرس':'صرف مستحق مشرف','amount'=>$amount,'spent_on'=>today()->toDateString(),'description'=>'صرف مباشر للمستحق رقم '.$record->id,'created_by'=>$r->user()->id]);});return response()->json(['success'=>true,'data'=>$record->fresh()]);}
public function summary(){$td=TeacherLessonDue::sum('amount');$tp=TeacherLessonDue::sum('paid_amount');$sd=SupervisorDue::sum('amount');$sp=SupervisorDue::sum('paid_amount');$b=Bonus::sum('amount');return response()->json(['success'=>true,'data'=>['teacher_due'=>$td,'teacher_paid'=>$tp,'teacher_remaining'=>max(0,$td-$tp),'supervisor_due'=>$sd,'supervisor_paid'=>$sp,'supervisor_remaining'=>max(0,$sd-$sp),'bonuses'=>$b,'total_due'=>$td+$sd,'total_paid'=>$tp+$sp,'total_remaining'=>max(0,($td+$sd)-($tp+$sp))]]);}
private function availableBalance(string $type,int $id):float{$due=$type==='teacher'?(float)TeacherLessonDue::where('teacher_id',$id)->sum(DB::raw('amount-paid_amount')):(float)SupervisorDue::where('supervisor_id',$id)->sum(DB::raw('amount-paid_amount'));$reserved=(float)WithdrawalRequest::where('recipient_type',$type)->where('recipient_id',$id)->whereIn('status',['pending','approved'])->sum('amount');return max(0,$due-$reserved);}
private function applyPayment(string $type,int $id,float $amount):void{$q=$type==='teacher'?TeacherLessonDue::where('teacher_id',$id)->whereColumn('paid_amount','<','amount')->orderBy('id')->lockForUpdate():SupervisorDue::where('supervisor_id',$id)->whereColumn('paid_amount','<','amount')->orderBy('id')->lockForUpdate();foreach($q->get() as $record){if($amount<=0)break;$remaining=max(0,(float)$record->amount-(float)$record->paid_amount);$take=min($remaining,$amount);$record->paid_amount=(float)$record->paid_amount+$take;$record->status=(float)$record->paid_amount>=(float)$record->amount?'paid':'partial';$record->save();$amount-=$take;}if($amount>0.009)throw new \RuntimeException('المبلغ المطلوب صرفه يتجاوز المستحق المتاح.');}
}
