import 'package:flutter/material.dart';
import '../../core/theme/app_theme.dart';
import '../../services/api_service.dart';
import '../students/students_screen.dart';
import '../teachers/teachers_screen.dart';
import '../payments/payments_screen.dart';
import '../expenses/expenses_screen.dart';
import '../reports/reports_screen.dart';
import '../schedules/schedules_screen.dart';
import '../attendance/attendance_screen.dart';
import '../subscriptions/subscriptions_screen.dart';
import '../lessons/lessons_screen.dart';
import '../supervisors/supervisors_screen.dart';
import '../finance/finance_screen.dart';
import '../auth/login_screen.dart';

class DashboardScreen extends StatefulWidget { const DashboardScreen({super.key}); @override State<DashboardScreen> createState()=>_DashboardScreenState(); }
class _DashboardScreenState extends State<DashboardScreen>{Map<String,dynamic>?data;bool loading=true;String?error;@override void initState(){super.initState();loadDashboard();}Future<void>loadDashboard()async{try{final r=await ApiService.get('dashboard');if(mounted)setState((){data=r;loading=false;error=null;});}catch(e){if(!mounted)return;setState((){error=e.toString().replaceFirst('Exception: ','');loading=false;});if(ApiService.token==null)Navigator.of(context).pushAndRemoveUntil(MaterialPageRoute(builder:(_)=>const LoginScreen()),(_)=>false);}}Future<void>logout()async{await ApiService.logout();if(mounted)Navigator.of(context).pushAndRemoveUntil(MaterialPageRoute(builder:(_)=>const LoginScreen()),(_)=>false);}void open(Widget w)=>Navigator.of(context).push(MaterialPageRoute(builder:(_)=>w));
@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:Text('${data?['academy_name']??'Online School Academy'}'),actions:[IconButton(onPressed:loading?null:loadDashboard,icon:const Icon(Icons.refresh)),IconButton(onPressed:logout,icon:const Icon(Icons.logout))]),drawer:Drawer(child:ListView(padding:EdgeInsets.zero,children:[const DrawerHeader(decoration:BoxDecoration(color:AppColors.black),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Icon(Icons.school,color:Colors.white,size:42),SizedBox(height:10),Text('Online School Academy',style:TextStyle(color:Colors.white,fontSize:20,fontWeight:FontWeight.bold)),Text('إدارة الأكاديمية',style:TextStyle(color:Colors.white70))])),_item(Icons.dashboard,'لوحة التحكم',null),_item(Icons.people,'الطلاب',const StudentsScreen()),_item(Icons.school,'المدرسون',const TeachersScreen()),_item(Icons.supervisor_account,'المشرفون',const SupervisorsScreen()),_item(Icons.menu_book,'الدروس والحصص',const LessonsScreen()),_item(Icons.calendar_month,'الجداول',const SchedulesScreen()),_item(Icons.fact_check,'الحضور',const AttendanceScreen()),_item(Icons.event_available,'الاشتراكات',const SubscriptionsScreen()),const Divider(),_item(Icons.payments,'المدفوعات',const PaymentsScreen()),_item(Icons.money_off,'المصروفات',const ExpensesScreen()),_item(Icons.account_balance_wallet,'المالية والمستحقات',const FinanceScreen()),_item(Icons.bar_chart,'التقارير المالية',const ReportsScreen())])),body:loading?const Center(child:CircularProgressIndicator()):error!=null?Center(child:Padding(padding:const EdgeInsets.all(24),child:Column(mainAxisSize:MainAxisSize.min,children:[Text(error!,textAlign:TextAlign.center),const SizedBox(height:16),FilledButton(onPressed:loadDashboard,child:const Text('إعادة المحاولة'))]))):RefreshIndicator(onRefresh:loadDashboard,child:GridView.count(crossAxisCount:2,padding:const EdgeInsets.all(16),crossAxisSpacing:12,mainAxisSpacing:12,children:[_card('الطلاب',data?['students'],Icons.people,()=>open(const StudentsScreen())),_card('المدرسون',data?['teachers'],Icons.school,()=>open(const TeachersScreen())),_card('حصص اليوم',data?['today_classes'],Icons.calendar_today,()=>open(const LessonsScreen())),_card('حضور اليوم',data?['today_attendance'],Icons.fact_check,()=>open(const AttendanceScreen())),_card('دخل الشهر',data?['monthly_income'],Icons.account_balance_wallet,()=>open(const PaymentsScreen())),_card('مصروفات الشهر',data?['monthly_expenses'],Icons.money_off,()=>open(const ExpensesScreen())),_card('تجديد خلال 7 أيام',data?['expiring_7_days'],Icons.warning_amber,()=>open(const SubscriptionsScreen()))]));
Widget _item(IconData i,String t,Widget?w)=>ListTile(leading:Icon(i),title:Text(t),onTap:(){Navigator.pop(context);if(w!=null)open(w);});Widget _card(String t,dynamic v,IconData i,VoidCallback f)=>Card(child:InkWell(onTap:f,child:Padding(padding:const EdgeInsets.all(16),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Icon(i,size:34,color:AppColors.red),const SizedBox(height:10),Text('${v??0}',style:const TextStyle(fontSize:27,fontWeight:FontWeight.bold)),Text(t)]))));}
